/*
 * This file is part of StyleBI.
 * Copyright (C) 2025  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

CREATE TABLE INETSOFT_ORG (
  ORG_ID VARCHAR(255) PRIMARY KEY,
  ORG_NAME VARCHAR(255) NOT NULL);

CREATE TABLE INETSOFT_USER (
  ORG_ID VARCHAR(255) NOT NULL,
  USER_NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255),
  PW_HASH VARCHAR(255) NOT NULL,
  PRIMARY KEY (ORG_ID, USER_NAME),
  FOREIGN KEY (ORG_ID) REFERENCES INETSOFT_ORG (ORG_ID));

CREATE TABLE INETSOFT_ROLE (
  ORG_ID VARCHAR(255) NOT NULL,
  ROLE_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ORG_ID, ROLE_NAME),
  FOREIGN KEY (ORG_ID) REFERENCES INETSOFT_ORG (ORG_ID));

CREATE TABLE INETSOFT_GROUP (
  ORG_ID VARCHAR(255) NOT NULL,
  GROUP_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ORG_ID, GROUP_NAME),
  FOREIGN KEY (ORG_ID) REFERENCES INETSOFT_ORG (ORG_ID));

CREATE TABLE INETSOFT_USER_ROLE (
  ORG_ID VARCHAR(255) NOT NULL,
  USER_NAME VARCHAR(255) NOT NULL,
  ROLE_NAME VARCHAR(255),
  PRIMARY KEY (ORG_ID, USER_NAME, ROLE_NAME),
  FOREIGN KEY (ORG_ID) REFERENCES INETSOFT_ORG (ORG_ID),
  FOREIGN KEY (ORG_ID, USER_NAME) REFERENCES INETSOFT_USER (ORG_ID, USER_NAME),
  FOREIGN KEY (ORG_ID, ROLE_NAME) REFERENCES INETSOFT_ROLE (ORG_ID, ROLE_NAME));

CREATE TABLE INETSOFT_GROUP_USER (
  ORG_ID VARCHAR(255) NOT NULL,
  GROUP_NAME VARCHAR(255) NOT NULL,
  USER_NAME VARCHAR(255),
  PRIMARY KEY (ORG_ID, GROUP_NAME, USER_NAME),
  FOREIGN KEY (ORG_ID) REFERENCES INETSOFT_ORG (ORG_ID),
  FOREIGN KEY (ORG_ID, GROUP_NAME) REFERENCES INETSOFT_GROUP (ORG_ID, GROUP_NAME),
  FOREIGN KEY (ORG_ID, USER_NAME) REFERENCES INETSOFT_USER (ORG_ID, USER_NAME));

INSERT INTO INETSOFT_ORG (ORG_ID, ORG_NAME) VALUES ('host-org', 'Host Organization');

INSERT INTO INETSOFT_ROLE (ORG_ID, ROLE_NAME) VALUES ('host-org', 'Site Admin');
INSERT INTO INETSOFT_ROLE (ORG_ID, ROLE_NAME) VALUES ('host-org', 'Org Admin');

INSERT INTO INETSOFT_USER (ORG_ID, USER_NAME, EMAIL, PW_HASH) VALUES ('host-org', 'admin', NULL, '$2y$10$VvRFL1nz.uKIEhRu5k6e2un3hdFQpcT/r17y97y7m6Dsdi6KCqsSC');

INSERT INTO INETSOFT_USER_ROLE (ORG_ID, USER_NAME, ROLE_NAME) VALUES ('host-org', 'admin', 'Site Admin');
