/*
 * This file is part of StyleBI.
 * Copyright (C) 2026  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package inetsoft.sree.security;

/*
 * Bug #77136: an organization id is the top-level folder of the organization's files in external
 * storage, but the server accepted ids naming the system folders (backup, heapdump, status),
 * ids colliding with the S3 base path, and ids with path characters such as "..".
 */

import inetsoft.sree.SreeEnv;
import inetsoft.util.Catalog;
import inetsoft.util.MessageException;
import inetsoft.util.config.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.function.Executable;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;
import org.mockito.MockedStatic;
import org.mockito.quality.Strictness;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@Tag("core")
class OrganizationIdRulesTest {
   @BeforeEach
   void setUp() {
      storage = mock(ExternalStorageConfig.class, withSettings().lenient());
      when(storage.getType()).thenReturn("filesystem");
      InetsoftConfig config = mock(InetsoftConfig.class, withSettings().lenient());
      when(config.getExternalStorage()).thenReturn(storage);
      configStatic = mockStatic(InetsoftConfig.class, withSettings().strictness(Strictness.LENIENT));
      configStatic.when(InetsoftConfig::getInstance).thenReturn(config);
   }

   @AfterEach
   void tearDown() {
      configStatic.close();
   }

   @ParameterizedTest
   @ValueSource(strings = { "backup", "BACKUP", "HeapDump", "status", "host-org", "HOST-ORG", "self" })
   void reservedIds_rejectedOnCreateAndRename(String id) {
      assertTrue(OrganizationIdRules.isReserved(id));
      assertRejected(() -> OrganizationIdRules.checkCreate(id), id);
      assertRejected(() -> OrganizationIdRules.checkRename("orgA", id), id);
   }

   @ParameterizedTest
   @ValueSource(strings = { "..", "a/b", "a\\b", "a b", "org_a", "" })
   void unsafeIds_rejected(String id) {
      assertRejected(() -> OrganizationIdRules.checkRename("orgA", id), id);

      if(!id.isEmpty()) {
         assertRejected(() -> OrganizationIdRules.checkCreate(id), id);
      }
   }

   @ParameterizedTest
   @ValueSource(strings = { "orgA", "org-1", "backup1", "mybackup", "data", "Sales2" })
   void validIds_accepted(String id) {
      assertDoesNotThrow(() -> OrganizationIdRules.checkCreate(id));
      assertDoesNotThrow(() -> OrganizationIdRules.checkRename("orgB", id));
   }

   @Test
   void emptyIdOnCreate_skipped() {
      // an empty id is generated by the caller (organizationN)
      assertDoesNotThrow(() -> OrganizationIdRules.checkCreate(""));
      assertDoesNotThrow(() -> OrganizationIdRules.checkCreate(null));
   }

   @Test
   void nullOrUnchangedIdOnRename_isNoChange() {
      // legacy organizations whose id predates the rules stay editable
      assertDoesNotThrow(() -> OrganizationIdRules.checkRename("backup", null));
      assertDoesNotThrow(() -> OrganizationIdRules.checkRename("backup", "backup"));
      assertDoesNotThrow(() -> OrganizationIdRules.checkRename("org_a", "org_a"));
      // a case-only change is a change, but orgA is not reserved
      assertDoesNotThrow(() -> OrganizationIdRules.checkRename("orga", "ORGA"));
   }

   @ParameterizedTest
   @ValueSource(strings = { "data", "DATA", "database" })
   void s3BasePath_idEqualToOrStartingWithBase_rejected(String id) {
      useS3Base("data/");
      assertTrue(OrganizationIdRules.isReserved(id));
      assertRejected(() -> OrganizationIdRules.checkCreate(id), id);
      assertRejected(() -> OrganizationIdRules.checkRename("orgA", id), id);
   }

   @Test
   void s3BasePath_otherIds_accepted() {
      useS3Base("/data");
      assertFalse(OrganizationIdRules.isReserved("dat"));
      assertFalse(OrganizationIdRules.isReserved("orgA"));
   }

   @Test
   void s3MultiSegmentBasePath_firstSegmentRejected() {
      useS3Base("a/b");
      assertTrue(OrganizationIdRules.isReserved("a"));
      assertTrue(OrganizationIdRules.isReserved("A"));
      assertFalse(OrganizationIdRules.isReserved("ab"));
      assertFalse(OrganizationIdRules.isReserved("b"));
   }

   @Test
   void s3EmptyBasePath_noBaseRule() {
      useS3Base("");
      assertFalse(OrganizationIdRules.isReserved("data"));
   }

   @Test
   void otherStorageTypes_noBaseRule() {
      S3Config s3 = mock(S3Config.class, withSettings().lenient());
      when(s3.getPath()).thenReturn("data");
      when(storage.getS3()).thenReturn(s3);
      when(storage.getType()).thenReturn("gcs");
      assertFalse(OrganizationIdRules.isReserved("data"));
   }

   // Bug #77137: the task save files of an organization are also in a folder named by its id in
   // each server save location, so an id naming a folder of a location path shares that folder
   @ParameterizedTest
   @CsvSource({
      "reports|Reports, reports",
      "reports|Reports, REPORTS",
      "archive/x|Archive, archive",
      "archive/x|Archive, x",
      "/var/reports|Var, var",
      "reports|Reports;reports/archive|Archive, archive",
   })
   void saveLocationFolder_rejectedOnCreateAndRename(String locations, String id) {
      try(MockedStatic<SreeEnv> ignored = useSaveLocations(locations)) {
         assertFalse(OrganizationIdRules.isReserved(id), "not a reserved id, a separate check");
         assertLocationRejected(() -> OrganizationIdRules.checkCreate(id), id);
         assertLocationRejected(() -> OrganizationIdRules.checkRename("orgA", id), id);
      }
   }

   @Test
   void saveLocationFolder_otherIdsAccepted() {
      try(MockedStatic<SreeEnv> ignored = useSaveLocations("reports|Reports;archive/x|Archive")) {
         assertDoesNotThrow(() -> OrganizationIdRules.checkCreate("rep"));
         assertDoesNotThrow(() -> OrganizationIdRules.checkCreate("reports2"));
         assertDoesNotThrow(() -> OrganizationIdRules.checkRename("orgA", "orgB"));
         // an unchanged legacy id can still be saved
         assertDoesNotThrow(() -> OrganizationIdRules.checkRename("reports", "reports"));
      }
   }

   @Test
   void ftpSaveLocation_notAFolderOfExternalStorage() {
      try(MockedStatic<SreeEnv> ignored = useSaveLocations("ftp://host/reports|FTP|user|pass")) {
         assertDoesNotThrow(() -> OrganizationIdRules.checkCreate("reports"));
      }
   }

   @Test
   void containsSaveLocation_folderIsOrHoldsALocation() {
      List<String> locations = List.of("reports", "/var/reports", "a/b/");

      assertTrue(OrganizationIdRules.containsSaveLocation("reports", locations));
      assertTrue(OrganizationIdRules.containsSaveLocation("Reports", locations));
      assertTrue(OrganizationIdRules.containsSaveLocation("var", locations));
      assertTrue(OrganizationIdRules.containsSaveLocation("/var/reports", locations));
      assertTrue(OrganizationIdRules.containsSaveLocation("a", locations));
      assertTrue(OrganizationIdRules.containsSaveLocation("a/b", locations));
      assertFalse(OrganizationIdRules.containsSaveLocation("rep", locations));
      assertFalse(OrganizationIdRules.containsSaveLocation("reports/orgA", locations));
      assertFalse(OrganizationIdRules.containsSaveLocation("a/b/orgA", locations));
      assertFalse(OrganizationIdRules.containsSaveLocation("", locations));
   }

   private static MockedStatic<SreeEnv> useSaveLocations(String locations) {
      MockedStatic<SreeEnv> sreeEnvStatic = mockStatic(SreeEnv.class);
      sreeEnvStatic.when(() -> SreeEnv.getProperty(anyString()))
         .thenAnswer(i -> "server.save.locations".equals(i.getArgument(0)) ? locations : null);
      return sreeEnvStatic;
   }

   private static void assertLocationRejected(Executable executable, String id) {
      MessageException thrown = assertThrows(MessageException.class, executable);
      assertEquals(Catalog.getCatalog().getString("em.security.saveLocationOrganizationID", id),
                   thrown.getMessage());
   }

   private void useS3Base(String path) {
      S3Config s3 = mock(S3Config.class, withSettings().lenient());
      when(s3.getPath()).thenReturn(path);
      when(storage.getType()).thenReturn("s3");
      when(storage.getS3()).thenReturn(s3);
   }

   private static void assertRejected(Executable executable, String id) {
      MessageException thrown = assertThrows(MessageException.class, executable);
      assertEquals(Catalog.getCatalog().getString("em.security.reservedOrganizationID", id),
                   thrown.getMessage());
   }

   private ExternalStorageConfig storage;
   private MockedStatic<InetsoftConfig> configStatic;
}
