/*
 * This file is part of StyleBI.
 * Copyright (C) 2026  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package inetsoft.report.composition.graph;

import inetsoft.graph.VContainer;
import inetsoft.graph.Visualizable;
import inetsoft.graph.visual.LabelFormVO;
import inetsoft.report.composition.execution.ViewsheetSandbox;
import inetsoft.test.*;
import inetsoft.uql.asset.*;
import inetsoft.uql.erm.AttributeRef;
import inetsoft.uql.viewsheet.*;
import inetsoft.uql.viewsheet.graph.*;
import inetsoft.util.Tool;
import inetsoft.util.UserMessage;
import inetsoft.web.viewsheet.event.OpenViewsheetEvent;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Bug #77805, one level above {@code Plotter.plotAndLayout}: a viewsheet chart whose target
 * line has a label pattern that fails must still be generated by
 * {@link ViewsheetSandbox#getVGraphPair} (GraphGenerator.addTarget + VGraphPair.initGraph0),
 * with the target labeled by its value as with the default label, instead of failing with
 * "Failed to generate chart".
 */
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = { BaseTestConfiguration.class, IntegrationTestConfiguration.class },
                      initializers = ConfigurationContextInitializer.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
@SreeHome(importResources = "/inetsoft/report/composition/EmbeddedVS1.zip")
@Tag("core")
@Tag("integration")
class ChartTargetLabelViewsheetTest {
   @Test
   void badTargetLabelStillGeneratesTheChart() throws Exception {
      String plain = targetLabel("ChartDefault", "{0}");
      assertTrue(plain.matches("[0-9.,]+"), "default label shows the value: " + plain);
      assertEquals(plain + " units", targetLabel("ChartUnits", "{0} units"),
                   "a valid custom label is applied");

      // format-time failure (TargetForm.createVisuals) and construction-time failure
      // (GraphTarget.createMessageFormat, unmatched braces)
      for(String label : new String[] { "{0,choice,}", "{0,choice" }) {
         Tool.clearUserMessage();
         assertEquals(plain, targetLabel("Chart" + label.length(), label),
                      "bad label " + label + " falls back to the value");
         UserMessage msg = Tool.getUserMessage();
         assertNotNull(msg, "the author is told label " + label + " failed");
         assertTrue(msg.getMessage().contains("target label"), msg.getMessage());
      }
   }

   private String targetLabel(String name, String label) throws Exception {
      ViewsheetSandbox box = vsResource.getRuntimeViewsheet().getViewsheetSandbox().orElseThrow();
      Viewsheet vs = box.getViewsheet();
      SourceInfo source =
         (SourceInfo) ((TableVSAssembly) vs.getAssembly(TABLE)).getSourceInfo().clone();
      ChartVSAssembly chart = new ChartVSAssembly(vs, name);
      chart.setSourceInfo(source);
      VSChartInfo info = chart.getVSChartInfo();
      VSChartDimensionRef dim =
         new VSChartDimensionRef(new ColumnRef(new AttributeRef(null, "type")));
      dim.setGroupColumnValue("type");
      info.addXField(dim);
      VSChartAggregateRef agg = new VSChartAggregateRef();
      agg.setColumnValue("wind");
      agg.setFormulaValue("Sum");
      info.addYField(agg);

      GraphTarget target = new GraphTarget();
      target.setField("Sum(wind)");
      target.setStrategy(new DynamicLineWrapper("100000"));
      target.setLabelFormats(label);
      chart.getChartDescriptor().addTarget(target);
      vs.addAssembly(chart);

      VGraphPair pair = assertDoesNotThrow(() -> box.getVGraphPair(name, true, null),
                                           "chart with target label " + label);
      assertNotNull(pair.getExpandedVGraph(), "chart with target label " + label + " has a graph");

      List<String> labels = new ArrayList<>();
      collectLabels(pair.getExpandedVGraph(), labels);
      assertEquals(1, labels.size(), "target labels for " + label + ": " + labels);
      return labels.get(0);
   }

   private static void collectLabels(Visualizable visual, List<String> labels) {
      if(visual instanceof LabelFormVO) {
         labels.add(((LabelFormVO) visual).getLabel());
      }

      if(visual instanceof VContainer container) {
         for(int i = 0; i < container.getVisualCount(); i++) {
            collectLabels(container.getVisual(i), labels);
         }
      }
   }

   private static OpenViewsheetEvent openViewsheetEvent() {
      OpenViewsheetEvent event = new OpenViewsheetEvent();
      event.setEntryId("1^128^__NULL__^EmbeddedVS1^host-org");
      event.setViewer(true);
      return event;
   }

   @RegisterExtension
   RuntimeViewsheetExtension vsResource = new RuntimeViewsheetExtension(openViewsheetEvent());

   private static final String TABLE = "TableView1";
}
