# shared configuration for the server and scheduler, generates the inetsoft.yaml configuration file
x-shared-config: &sharedenv
  # the master password used for PBKDF2 encryption of sensitive data
  # (not part of inetsoft.yaml, but required by all containers)
  INETSOFT_MASTER_PASSWORD: "some_arbitrary_token"
  # the directory used for local plugin storage
  INETSOFTCONFIG_PLUGINDIRECTORY: "/var/lib/inetsoft/plugins"
  # use the MapDB key-value engine
  INETSOFTCONFIG_KEYVALUE_TYPE: "mapdb"
  # the path to the directory containing the MapDB database files
  INETSOFTCONFIG_KEYVALUE_MAPDB_DIRECTORY: "/var/lib/inetsoft/kv"
  # use the shared filesystem blob engine
  INETSOFTCONFIG_BLOB_TYPE: "filesystem"
  # the path to the local cache for blobs
  INETSOFTCONFIG_BLOB_CACHEDIRECTORY: "/var/lib/inetsoft/blob-cache"
  # the path to shared blob storage directory
  INETSOFTCONFIG_BLOB_FILESYSTEM_DIRECTORY: "/var/lib/inetsoft/blob"
  # use a shared directory for external storage
  INETSOFTCONFIG_EXTERNALSTORAGE_TYPE: "filesystem"
  # the path to the external storage shared directory
  INETSOFTCONFIG_EXTERNALSTORAGE_FILESYSTEM_DIRECTORY: "/var/lib/inetsoft/files"

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: inetsoft
      POSTGRES_PASSWORD: inetsoft
      POSTGRES_DB: orders
    volumes:
      - "./orders.sql:/docker-entrypoint-initdb.d/orders.sql:ro"
  storage_perms:
    # this container changes the owner of the shared volumes
    image: busybox:latest
    restart: no
    volumes:
      - "inetsoft_kv:/tmp/inetsoft_kv"
      - "inetsoft_blob:/tmp/inetsoft_blob"
      - "inetsoft_files:/tmp/inetsoft_files"
    command: [ "/bin/sh", "-c", "chown -R 1000:1000 /tmp/inetsoft_kv /tmp/inetsoft_blob /tmp/inetsoft_files"]
  storage:
    # this container initializes the storage before the first start
    image: "${STYLEBI_DOCKER_IMAGE:-ghcr.io/inetsoft-technology/stylebi-community:latest}"
    restart: no
    volumes:
      - "inetsoft_kv:/var/lib/inetsoft/kv"
      - "inetsoft_blob:/var/lib/inetsoft/blob"
      - "inetsoft_files:/var/lib/inetsoft/files"
    environment:
      # initialize storage with these properties
      # the password for the "admin" user
      INETSOFT_ADMIN_PASSWORD: "admin"
      # set the cluster mode flag, required when using Docker (server.type property)
      INETSOFTENV_SERVER_TYPE: "server_cluster"
      # Additional application properties, like the mail server can be added here
#      INETSOFTENV_MAIL_SMTP_HOST: "mail.example.com"
#      INETSOFTENV_MAIL_SMTP_PORT: "587"
      # Java command line options, overridden to set min and max heap memory
      JAVA_MEMORY_OPTS: "-Xms1g -Xmx1g"
      <<: *sharedenv
    command:
      - "init"
    depends_on:
      storage_perms:
        condition: service_completed_successfully
  server:
    image: "${STYLEBI_DOCKER_IMAGE:-ghcr.io/inetsoft-technology/stylebi-community:latest}"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "inetsoft_kv:/var/lib/inetsoft/kv"
      - "inetsoft_blob:/var/lib/inetsoft/blob"
      - "inetsoft_files:/var/lib/inetsoft/files"
    environment:
      # Java command line options, overridden to set min and max heap memory
      JAVA_MEMORY_OPTS: "-Xms2g -Xmx2g"
      <<: *sharedenv
    command:
      - "server"
    depends_on:
      storage:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    healthcheck:
      test: "curl --fail http://localhost:8081/health/readiness || exit 1"
      interval: 20s
      retries: 10
      start_period: 20s
      timeout: 10s
  scheduler:
    image: "${STYLEBI_DOCKER_IMAGE:-ghcr.io/inetsoft-technology/stylebi-community:latest}"
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - "inetsoft_kv:/var/lib/inetsoft/kv"
      - "inetsoft_blob:/var/lib/inetsoft/blob"
      - "inetsoft_files:/var/lib/inetsoft/files"
    environment:
      # Java command line options, overridden to set min and max heap memory
      JAVA_MEMORY_OPTS: "-Xms1g -Xmx1g"
      <<: *sharedenv
    command:
      - "scheduler"
volumes:
  inetsoft_kv:
  inetsoft_blob:
  inetsoft_files:
