/*
 * This file is part of StyleBI.
 * Copyright (C) 2024  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package inetsoft.uql.jdbc.util;

import inetsoft.uql.VariableTable;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Regression tests for Bug #76822 (Redmine WSQ-008) — SQL injection via a
 * {@code $(name)} placeholder quoted inside a string literal in the SQL text
 * handed to {@link VarSQL#replaceVariables(String, VariableTable)}.
 */
@Tag("core")
public class VarSQLTest {

   /**
    * Whole-literal quoted placeholder, value contains a genuine embedded
    * apostrophe. Must not break the SQL and must round-trip to the original
    * value when the doubled quote is later unescaped by the SQL engine.
    */
   @Test
   void quotedPlaceholder_valueWithApostrophe_isEscapedNotBroken() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("companyName", "Big Ed's BBQ");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = '$(companyName)'", vars);

      assertEquals(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = 'Big Ed''s BBQ'", result);
      // the value was spliced as an escaped literal, not registered as a
      // bind parameter — confirm no parameter was recorded for it
      assertTrue(varSql.getParameterNames().isEmpty());
   }

   /**
    * Whole-literal quoted placeholder, value is a boolean-bypass SQL
    * injection payload. The escaped value must stay inert literal text —
    * it must not be able to close the string literal or alter the query's
    * logical structure.
    */
   @Test
   void quotedPlaceholder_booleanBypassPayload_staysInertLiteral() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("companyName", "x' OR '1'='1");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = '$(companyName)'", vars);

      assertEquals(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = 'x'' OR ''1''=''1'", result);
      // exactly one string literal remains in the WHERE clause — the
      // payload never terminated it early
      assertEquals(1, countOccurrences(result, "COMPANY_NAME ="));
   }

   /**
    * Partial-literal case: the placeholder shares its quoted literal with
    * other literal content, as generated by ConditionListHandler for
    * STARTING_WITH/CONTAINS/LIKE (e.g. '$(name)%'). An apostrophe/injection
    * payload in the value must not be able to escape past the trailing '%'
    * or the closing quote.
    */
   @Test
   void partialLiteralPlaceholder_startingWithPattern_escapesValueOnly() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("_condition_0", "x' OR '1'='1");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME LIKE '$(_condition_0)%'", vars);

      assertEquals(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME LIKE 'x'' OR ''1''=''1%'", result);
      assertTrue(varSql.getParameterNames().isEmpty());
   }

   /**
    * MySQL/MariaDB (default sql_mode) treat backslash as a string-literal
    * escape character, so a value containing a trailing backslash must not
    * be able to consume the literal's own closing quote as an escaped
    * character there. Only applies when the caller opts in via
    * setBackslashIsEscapeChar(true), matching how JDBCHandler detects the
    * MySQL dialect before calling replaceVariables().
    */
   @Test
   void quotedPlaceholder_mysqlDialect_trailingBackslashDoubled() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      varSql.setBackslashIsEscapeChar(true);
      VariableTable vars = new VariableTable();
      vars.put("companyName", "foo\\");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = '$(companyName)' AND 1=1", vars);

      assertEquals(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = 'foo\\\\' AND 1=1", result);
   }

   /**
    * ANSI-standard dialects (Postgres with standard_conforming_strings,
    * Oracle, SQL Server, DB2, etc.) do not treat backslash as special inside
    * a '...' literal, so a value containing a genuine literal backslash
    * (e.g. a Windows path) must round-trip unmodified — only the quote
    * character is doubled, never the backslash. This is the default
    * (setBackslashIsEscapeChar not called), matching JDBCHandler's behavior
    * for every non-MySQL dialect.
    */
   @Test
   void quotedPlaceholder_ansiDialect_backslashNotDoubled() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("path", "C:\\Users\\bob");

      String result = varSql.replaceVariables(
         "SELECT * FROM FILES WHERE PATH = '$(path)'", vars);

      assertEquals(
         "SELECT * FROM FILES WHERE PATH = 'C:\\Users\\bob'", result);
   }

   /**
    * Unquoted placeholder path must remain unchanged: it still binds
    * through a real parameter (params/names), not literal splicing.
    */
   @Test
   void unquotedPlaceholder_stillUsesBindParameter() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("companyName", "x' OR '1'='1");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = $(companyName)", vars);

      assertEquals("SELECT * FROM CUSTOMERS WHERE COMPANY_NAME =  ? ", result);
      assertEquals(1, varSql.getParameterValues().size());
      assertEquals("x' OR '1'='1", varSql.getParameterValues().get(0));
   }

   /**
    * The $(@name) "embed" form is an intentional raw-SQL-fragment
    * embedding feature (not end-user data) and stays unescaped.
    */
   @Test
   void embedPlaceholder_staysRawAndUnescaped() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("clause", "COMPANY_NAME = 'ACME'");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE $(@clause)", vars);

      assertEquals("SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = 'ACME'", result);
   }

   // ---------------------------------------------------------------------
   // Bug #76864 — SQLType.STRING (tabular / Mongo JSON query text) path.
   // Values are spliced as literals, so they must be escaped JSON-style:
   // \ -> \\, ' -> \', " -> \" (SQL quote doubling is not an escape in bson).
   // ---------------------------------------------------------------------

   private static VarSQL jsonStringVarSql() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STRING);
      varSql.setLiteralEscapeStyle(VarSQL.LiteralEscapeStyle.JSON);
      return varSql;
   }

   private static String replaceJson(String template, String name, Object value) {
      VariableTable vars = new VariableTable();
      vars.put(name, value);
      return jsonStringVarSql().replaceVariables(template, vars);
   }

   @Test
   void jsonUnquoted_apostropheValue_isBackslashEscaped() {
      assertEquals("{name:  'O\\'Brien' }", replaceJson("{name: $(p)}", "p", "O'Brien"));
   }

   @Test
   void jsonUnquoted_injectionPayload_staysInsideLiteral() {
      assertEquals("{name:  'x\\', admin: \\'1' }",
                   replaceJson("{name: $(p)}", "p", "x', admin: '1"));
   }

   @Test
   void jsonUnquoted_trailingBackslash_isDoubled() {
      assertEquals("{name:  'x\\\\' , b: 1}", replaceJson("{name: $(p), b: 1}", "p", "x\\"));
   }

   @Test
   void jsonUnquoted_doubleQuote_isEscaped() {
      assertEquals("{name:  'a\\\"b' }", replaceJson("{name: $(p)}", "p", "a\"b"));
   }

   @Test
   void jsonUnquoted_arrayInList_escapesEveryElement() {
      assertEquals("name in ( 'O\\'Brien' , 'x\\\\' )",
                   replaceJson("name in $(p)", "p", new String[] { "O'Brien", "x\\" }));
   }

   @Test
   void jsonUnquoted_arrayScalarContext_escapesFirstElement() {
      assertEquals("{name:  'O\\'Brien' }",
                   replaceJson("{name: $(p)}", "p", new String[] { "O'Brien", "y" }));
   }

   @Test
   void jsonSingleQuoted_apostropheAndBackslash_areBackslashEscaped() {
      assertEquals("{name: 'O\\'Brien', b: 'x\\\\'}", jsonStringVarSql().replaceVariables(
         "{name: '$(p)', b: '$(q)'}", vars("p", "O'Brien", "q", "x\\")));
   }

   @Test
   void jsonDoubleQuoted_doubleQuoteAndBackslash_areBackslashEscaped() {
      assertEquals("{name: \"a\\\"b\", b: \"x\\\\\"}", jsonStringVarSql().replaceVariables(
         "{name: \"$(p)\", b: \"$(q)\"}", vars("p", "a\"b", "q", "x\\")));
   }

   @Test
   void jsonUnquoted_numberAndPlainString_unchanged() {
      assertEquals("{n:  42 }", replaceJson("{n: $(p)}", "p", 42));
      assertEquals("{s:  'plain' }", replaceJson("{s: $(p)}", "p", "plain"));
   }

   @Test
   void jsonEmbedPlaceholder_staysRaw() {
      assertEquals("{a: 'x', b: 1}", replaceJson("{$(@frag), b: 1}", "frag", "a: 'x'"));
   }

   /**
    * JDBC (default SQL escape style) quoted path must keep #76822's
    * quote doubling, never JSON backslash escaping.
    */
   @Test
   void sqlStyleDefault_quotedPlaceholder_stillQuoteDoubles() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);

      assertEquals("WHERE A = 'O''Brien' AND B = 'C:\\x'", varSql.replaceVariables(
         "WHERE A = '$(p)' AND B = '$(q)'", vars("p", "O'Brien", "q", "C:\\x")));
   }

   private static VariableTable vars(Object... kv) {
      VariableTable vars = new VariableTable();

      for(int i = 0; i < kv.length; i += 2) {
         vars.put((String) kv[i], kv[i + 1]);
      }

      return vars;
   }

   private static int countOccurrences(String haystack, String needle) {
      int count = 0;
      int idx = 0;

      while((idx = haystack.indexOf(needle, idx)) != -1) {
         count++;
         idx += needle.length();
      }

      return count;
   }
}
