/*
 * This file is part of StyleBI.
 * Copyright (C) 2024  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package inetsoft.uql.jdbc.util;

import inetsoft.uql.VariableTable;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Regression tests for Bug #76822 (Redmine WSQ-008) — SQL injection via a
 * {@code $(name)} placeholder quoted inside a string literal in the SQL text
 * handed to {@link VarSQL#replaceVariables(String, VariableTable)}.
 */
@Tag("core")
public class VarSQLTest {

   /**
    * Whole-literal quoted placeholder, value contains a genuine embedded
    * apostrophe. Must not break the SQL and must round-trip to the original
    * value when the doubled quote is later unescaped by the SQL engine.
    */
   @Test
   void quotedPlaceholder_valueWithApostrophe_isEscapedNotBroken() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("companyName", "Big Ed's BBQ");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = '$(companyName)'", vars);

      assertEquals(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = 'Big Ed''s BBQ'", result);
      // the value was spliced as an escaped literal, not registered as a
      // bind parameter — confirm no parameter was recorded for it
      assertTrue(varSql.getParameterNames().isEmpty());
   }

   /**
    * Whole-literal quoted placeholder, value is a boolean-bypass SQL
    * injection payload. The escaped value must stay inert literal text —
    * it must not be able to close the string literal or alter the query's
    * logical structure.
    */
   @Test
   void quotedPlaceholder_booleanBypassPayload_staysInertLiteral() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("companyName", "x' OR '1'='1");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = '$(companyName)'", vars);

      assertEquals(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = 'x'' OR ''1''=''1'", result);
      // exactly one string literal remains in the WHERE clause — the
      // payload never terminated it early
      assertEquals(1, countOccurrences(result, "COMPANY_NAME ="));
   }

   /**
    * Partial-literal case: the placeholder shares its quoted literal with
    * other literal content, as generated by ConditionListHandler for
    * STARTING_WITH/CONTAINS/LIKE (e.g. '$(name)%'). An apostrophe/injection
    * payload in the value must not be able to escape past the trailing '%'
    * or the closing quote.
    */
   @Test
   void partialLiteralPlaceholder_startingWithPattern_escapesValueOnly() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("_condition_0", "x' OR '1'='1");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME LIKE '$(_condition_0)%'", vars);

      assertEquals(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME LIKE 'x'' OR ''1''=''1%'", result);
      assertTrue(varSql.getParameterNames().isEmpty());
   }

   /**
    * MySQL/MariaDB (default sql_mode) treat backslash as a string-literal
    * escape character, so a value containing a trailing backslash must not
    * be able to consume the literal's own closing quote as an escaped
    * character there. Only applies when the caller opts in via
    * setBackslashIsEscapeChar(true), matching how JDBCHandler detects the
    * MySQL dialect before calling replaceVariables().
    */
   @Test
   void quotedPlaceholder_mysqlDialect_trailingBackslashDoubled() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      varSql.setBackslashIsEscapeChar(true);
      VariableTable vars = new VariableTable();
      vars.put("companyName", "foo\\");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = '$(companyName)' AND 1=1", vars);

      assertEquals(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = 'foo\\\\' AND 1=1", result);
   }

   /**
    * ANSI-standard dialects (Postgres with standard_conforming_strings,
    * Oracle, SQL Server, DB2, etc.) do not treat backslash as special inside
    * a '...' literal, so a value containing a genuine literal backslash
    * (e.g. a Windows path) must round-trip unmodified — only the quote
    * character is doubled, never the backslash. This is the default
    * (setBackslashIsEscapeChar not called), matching JDBCHandler's behavior
    * for every non-MySQL dialect.
    */
   @Test
   void quotedPlaceholder_ansiDialect_backslashNotDoubled() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("path", "C:\\Users\\bob");

      String result = varSql.replaceVariables(
         "SELECT * FROM FILES WHERE PATH = '$(path)'", vars);

      assertEquals(
         "SELECT * FROM FILES WHERE PATH = 'C:\\Users\\bob'", result);
   }

   /**
    * Unquoted placeholder path must remain unchanged: it still binds
    * through a real parameter (params/names), not literal splicing.
    */
   @Test
   void unquotedPlaceholder_stillUsesBindParameter() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("companyName", "x' OR '1'='1");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = $(companyName)", vars);

      assertEquals("SELECT * FROM CUSTOMERS WHERE COMPANY_NAME =  ? ", result);
      assertEquals(1, varSql.getParameterValues().size());
      assertEquals("x' OR '1'='1", varSql.getParameterValues().get(0));
   }

   /**
    * The $(@name) "embed" form is an intentional raw-SQL-fragment
    * embedding feature (not end-user data) and stays unescaped.
    */
   @Test
   void embedPlaceholder_staysRawAndUnescaped() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);
      VariableTable vars = new VariableTable();
      vars.put("clause", "COMPANY_NAME = 'ACME'");

      String result = varSql.replaceVariables(
         "SELECT * FROM CUSTOMERS WHERE $(@clause)", vars);

      assertEquals("SELECT * FROM CUSTOMERS WHERE COMPANY_NAME = 'ACME'", result);
   }

   // ---------------------------------------------------------------------
   // Bug #76864 / #77105 — SQLType.STRING (tabular / Mongo JSON query text)
   // path. String values are encoded fail-closed: every ASCII char outside
   // [A-Za-z0-9 _], and the first char, is written as a backslash-u-XXXX
   // escape, which bson decodes inside a string and rejects in structural
   // context. Non-String values get no first-char encoding. These cases used
   // to pin the #76864 backslash-prefix form (\' \" \\); they now pin the
   // #77105 form. The semantic round-trip (value parses back exactly) is
   // asserted with the real bson parser in MongoQueryVariableEscapeTest.
   // ---------------------------------------------------------------------

   private static VarSQL jsonStringVarSql() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STRING);
      varSql.setLiteralEscapeStyle(VarSQL.LiteralEscapeStyle.JSON);
      return varSql;
   }

   private static String replaceJson(String template, String name, Object value) {
      VariableTable vars = new VariableTable();
      vars.put(name, value);
      return jsonStringVarSql().replaceVariables(template, vars);
   }

   @Test
   void jsonUnquoted_apostropheValue_isUnicodeEscaped() {
      assertEquals("{name:  '\\u004f\\u0027Brien' }",
                   replaceJson("{name: $(p)}", "p", "O'Brien"));
   }

   @Test
   void jsonUnquoted_injectionPayload_staysInsideLiteral() {
      assertEquals("{name:  '\\u0078\\u0027\\u002c admin\\u003a \\u00271' }",
                   replaceJson("{name: $(p)}", "p", "x', admin: '1"));
   }

   @Test
   void jsonUnquoted_trailingBackslash_isUnicodeEscaped() {
      assertEquals("{name:  '\\u0078\\u005c' , b: 1}",
                   replaceJson("{name: $(p), b: 1}", "p", "x\\"));
   }

   @Test
   void jsonUnquoted_doubleQuote_isUnicodeEscaped() {
      assertEquals("{name:  '\\u0061\\u0022b' }", replaceJson("{name: $(p)}", "p", "a\"b"));
   }

   @Test
   void jsonUnquoted_arrayInList_escapesEveryElement() {
      assertEquals("name in ( '\\u004f\\u0027Brien' , '\\u0078\\u005c' )",
                   replaceJson("name in $(p)", "p", new String[] { "O'Brien", "x\\" }));
   }

   @Test
   void jsonUnquoted_arrayScalarContext_escapesFirstElement() {
      assertEquals("{name:  '\\u004f\\u0027Brien' }",
                   replaceJson("{name: $(p)}", "p", new String[] { "O'Brien", "y" }));
   }

   @Test
   void jsonSingleQuoted_apostropheAndBackslash_areUnicodeEscaped() {
      assertEquals("{name: '\\u004f\\u0027Brien', b: '\\u0078\\u005c'}",
                   jsonStringVarSql().replaceVariables(
                      "{name: '$(p)', b: '$(q)'}", vars("p", "O'Brien", "q", "x\\")));
   }

   @Test
   void jsonDoubleQuoted_doubleQuoteAndBackslash_areUnicodeEscaped() {
      assertEquals("{name: \"\\u0061\\u0022b\", b: \"\\u0078\\u005c\"}",
                   jsonStringVarSql().replaceVariables(
                      "{name: \"$(p)\", b: \"$(q)\"}", vars("p", "a\"b", "q", "x\\")));
   }

   @Test
   void jsonUnquoted_numberUnchanged_plainStringFirstCharEncoded() {
      assertEquals("{n:  42 }", replaceJson("{n: $(p)}", "p", 42));
      assertEquals("{s:  '\\u0070lain' }", replaceJson("{s: $(p)}", "p", "plain"));
   }

   /**
    * Bug #77105: in a quoted position a Number keeps its text (no first-char
    * rule), a String always starts with an escape, and non-ASCII passes
    * through unchanged.
    */
   @Test
   void jsonQuoted_firstCharRuleOnlyForStrings_nonAsciiPassesThrough() {
      assertEquals("{n: '18', s: '\\u00318', u: '\\u0074rue 日本'}",
                   jsonStringVarSql().replaceVariables(
                      "{n: '$(p)', s: '$(q)', u: '$(r)'}",
                      vars("p", 18, "q", "18", "r", "true 日本")));
   }

   /**
    * Bug #77105 round 1: in JSON style a quoted-position Number, Boolean or
    * Date is emitted unescaped (as {@link VarSQL#toSQLConstant} does for
    * non-String values); its text cannot close a string or regex literal.
    * Any other non-String value is encoded like a String (first-char rule).
    */
   @Test
   void jsonQuoted_numberBooleanDateUnescaped_otherObjectsEncodedLikeString() {
      assertEquals("{a: '-3', b: '1.5', c: '1E+5', d: '-0.25', e: 'true'}",
                   jsonStringVarSql().replaceVariables(
                      "{a: '$(a)', b: '$(b)', c: '$(c)', d: '$(d)', e: '$(e)'}",
                      vars("a", -3, "b", 1.5, "c", new java.math.BigDecimal("1E+5"),
                           "d", new java.math.BigDecimal("-0.25"), "e", Boolean.TRUE)));

      java.sql.Timestamp ts = java.sql.Timestamp.valueOf("2024-01-02 03:04:05.0");
      assertEquals("{t: '2024-01-02 03:04:05.0'}",
                   jsonStringVarSql().replaceVariables("{t: '$(t)'}", vars("t", ts)));

      assertEquals("{o: '\\u004dinKey'}",
                   jsonStringVarSql().replaceVariables(
                      "{o: '$(o)'}", vars("o", new StringBuilder("MinKey"))));
   }

   @Test
   void jsonEmbedPlaceholder_staysRaw() {
      assertEquals("{a: 'x', b: 1}", replaceJson("{$(@frag), b: 1}", "frag", "a: 'x'"));
   }

   /**
    * JDBC (default SQL escape style) quoted path must keep #76822's
    * quote doubling, never JSON backslash escaping.
    */
   @Test
   void sqlStyleDefault_quotedPlaceholder_stillQuoteDoubles() {
      VarSQL varSql = new VarSQL();
      varSql.setSQLType(VarSQL.SQLType.STATEMENT);

      assertEquals("WHERE A = 'O''Brien' AND B = 'C:\\x'", varSql.replaceVariables(
         "WHERE A = '$(p)' AND B = '$(q)'", vars("p", "O'Brien", "q", "C:\\x")));
   }

   private static VariableTable vars(Object... kv) {
      VariableTable vars = new VariableTable();

      for(int i = 0; i < kv.length; i += 2) {
         vars.put((String) kv[i], kv[i + 1]);
      }

      return vars;
   }

   private static int countOccurrences(String haystack, String needle) {
      int count = 0;
      int idx = 0;

      while((idx = haystack.indexOf(needle, idx)) != -1) {
         count++;
         idx += needle.length();
      }

      return count;
   }
}
