/*
 * This file is part of StyleBI.
 * Copyright (C) 2026  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package inetsoft.web.binding.controller;

import inetsoft.analytic.composition.ViewsheetService;
import inetsoft.report.BaseLayout;
import inetsoft.report.CellBinding;
import inetsoft.report.TableCellBinding;
import inetsoft.report.TableDataPath;
import inetsoft.report.TableLayout;
import inetsoft.uql.service.DataSourceRegistry;
import inetsoft.uql.viewsheet.CalcTableVSAssembly;
import inetsoft.uql.viewsheet.internal.CalcTableVSAssemblyInfo;
import inetsoft.web.binding.handler.TableLayoutHandler;
import inetsoft.web.binding.handler.VSAssemblyInfoHandler;
import inetsoft.web.binding.handler.VSCalcCellScriptHandler;
import inetsoft.web.binding.handler.VSColumnHandler;
import inetsoft.web.binding.handler.VSRowColGroupHandler;
import inetsoft.web.binding.model.table.CellBindingInfo;
import inetsoft.web.binding.service.DataRefModelFactoryService;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Regression coverage for the get_calc_layout / get_cell_binding "runtimeName always null"
 * defect: {@code getCellBindingInfo(assembly, row, col)} built its {@code CellBindingInfo} via
 * {@code createCellBinding(bind)} but never called {@code setRuntimeName(...)} on the result,
 * unlike its two sibling methods in this same class ({@code createCellBindingCommand} and
 * {@code getCellBindingInfos}), which both do. This is the only place able to exercise the real
 * method against a real {@link TableLayout}/{@link TableCellBinding} -- {@code CalcTableServiceTest}
 * mocks {@code VSTableLayoutService} entirely.
 */
@Tag("core")
class VSTableLayoutServiceTest {
   @Test
   void reportsAnExplicitCellName() {
      TableLayout layout = new TableLayout();
      layout.setColCount(1);
      BaseLayout.Region region = layout.new Region();
      region.setRowCount(1);
      layout.addRegion(new TableDataPath(-1, TableDataPath.DETAIL), region);

      TableCellBinding bind = new TableCellBinding(CellBinding.BIND_COLUMN, "REGION");
      bind.setBType(TableCellBinding.GROUP);
      bind.setCellName("MyRegionCell");
      layout.setCellBinding(0, 0, bind);

      CellBindingInfo info = getCellBindingInfo(layout, 0, 0);

      assertEquals("MyRegionCell", info.getRuntimeName());
   }

   @Test
   void reportsAnAutoGeneratedNameWhenNoneIsExplicitlySet() {
      TableLayout layout = new TableLayout();
      layout.setColCount(1);
      BaseLayout.Region region = layout.new Region();
      region.setRowCount(1);
      layout.addRegion(new TableDataPath(-1, TableDataPath.DETAIL), region);

      TableCellBinding bind = new TableCellBinding(CellBinding.BIND_COLUMN, "REGION");
      bind.setBType(TableCellBinding.GROUP);
      layout.setCellBinding(0, 0, bind);

      CellBindingInfo info = getCellBindingInfo(layout, 0, 0);

      assertNotNull(info.getRuntimeName(), "runtimeName must not be left null");
      assertEquals(layout.getRuntimeCellName(bind), info.getRuntimeName());
   }

   /**
    * Two GROUP cells bound to the same column with no explicit name auto-generate the same
    * base name; {@code TableLayout.getRuntimeCellName} disambiguates the second with a
    * {@code _1} suffix. That disambiguation must survive through this method, since it is
    * exactly the value {@code $Name} cross-cell references resolve against.
    */
   @Test
   void disambiguatesCollidingAutoGeneratedNames() {
      TableLayout layout = new TableLayout();
      layout.setColCount(1);
      BaseLayout.Region region = layout.new Region();
      region.setRowCount(2);
      layout.addRegion(new TableDataPath(-1, TableDataPath.DETAIL), region);

      TableCellBinding first = new TableCellBinding(CellBinding.BIND_COLUMN, "REGION");
      first.setBType(TableCellBinding.GROUP);
      layout.setCellBinding(0, 0, first);

      TableCellBinding second = new TableCellBinding(CellBinding.BIND_COLUMN, "REGION");
      second.setBType(TableCellBinding.GROUP);
      layout.setCellBinding(1, 0, second);

      CellBindingInfo firstInfo = getCellBindingInfo(layout, 0, 0);
      CellBindingInfo secondInfo = getCellBindingInfo(layout, 1, 0);

      assertEquals("REGION", firstInfo.getRuntimeName());
      assertEquals("REGION_1", secondInfo.getRuntimeName());
   }

   private static CellBindingInfo getCellBindingInfo(TableLayout layout, int row, int col) {
      CalcTableVSAssemblyInfo info = mock(CalcTableVSAssemblyInfo.class);
      when(info.getTableLayout()).thenReturn(layout);
      CalcTableVSAssembly assembly = mock(CalcTableVSAssembly.class);
      when(assembly.getInfo()).thenReturn(info);

      VSTableLayoutService service = new VSTableLayoutService(
         mock(VSRowColGroupHandler.class), mock(DataRefModelFactoryService.class),
         mock(VSAssemblyInfoHandler.class), mock(TableLayoutHandler.class),
         mock(VSCalcCellScriptHandler.class), mock(VSColumnHandler.class),
         mock(ViewsheetService.class), mock(DataSourceRegistry.class));

      return service.getCellBindingInfo(assembly, row, col);
   }
}
