/*
 * This file is part of StyleBI.
 * Copyright (C) 2026  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package inetsoft.web.admin.security.action;

/*
 * Bug #77251 / #77252: drives the real ActionPermissionController.setPermissions() with the real
 * ActionPermissionService.getActionTree(principal) and the real ResourcePermissionService against
 * a real security provider (no hand-built tree), in multi-tenant mode.
 *
 * view-components.json is generated by the web module's frontend build and is not on core's test
 * classpath, so view-components-snapshot.json (next to this class) is a copy of the generated file.
 * It is stored under a different name/package so ComponentAuthorizationService in other tests
 * does not pick it up.
 *
 * Personas:
 *   orgAdmin - org user holding the global "Organization Administrator" role (not a site admin)
 *   delegate - plain org user whose only grant is ACCESS on EM_COMPONENT:settings/security/actions
 *   grantee  - plain org user used as the target of a legitimate grant
 */

import com.fasterxml.jackson.databind.ObjectMapper;
import inetsoft.report.internal.license.LicenseManager;
import inetsoft.sree.internal.SUtil;
import inetsoft.sree.internal.cluster.Cluster;
import inetsoft.sree.portal.PortalThemesManager;
import inetsoft.sree.security.*;
import inetsoft.sree.security.support.SecurityTestDataBuilder;
import inetsoft.test.*;
import inetsoft.uql.util.Identity;
import inetsoft.util.DataSpace;
import inetsoft.util.ThreadContext;
import inetsoft.web.admin.authz.ComponentAuthorizationService;
import inetsoft.web.admin.authz.ViewComponent;
import inetsoft.web.admin.content.repository.ResourcePermissionService;
import inetsoft.web.admin.security.ResourcePermissionModel;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.Mockito;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.io.InputStream;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = { BaseTestConfiguration.class },
                      initializers = ConfigurationContextInitializer.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
@SreeHome
@Tag("core")
class ActionPermissionControllerRealTreeTest {
   private static final String ORG_NAME = "realTreeActionsOrg";
   private static final String ORG_ID = "real_tree_actions_org_id";
   private static final IdentityID ORG_ADMIN_ROLE = new IdentityID("Organization Administrator", null);
   private static final String SETTINGS_GENERAL = "settings/general";
   private static final String SETTINGS_ACTIONS = "settings/security/actions";
   private static final String SETTINGS_USERS = "settings/security/users";
   private static final String SETTINGS_SECURITY = "settings/security";

   private static SecurityTestDataBuilder builder;
   private static SRPrincipal orgAdmin;
   private static SRPrincipal delegate;
   private static ActionPermissionController controller;

   private MockedStatic<SUtil> sutil;
   private MockedStatic<LicenseManager> license;

   @BeforeAll
   static void setupAll() throws Exception {
      builder = SecurityTestDataBuilder.create()
         .addOrg(ORG_NAME, ORG_ID)
         .addUser("orgAdminUser", ORG_ID, "password")
         .addUser("delegateUser", ORG_ID, "password")
         .addUser("granteeUser", ORG_ID, "password")
         .addUser("victimUser", ORG_ID, "password")
         .grantPermission(ResourceType.EM_COMPONENT, SETTINGS_ACTIONS, ResourceAction.ACCESS,
                          "delegateUser", Identity.USER, ORG_ID);
      builder.setup();

      orgAdmin = builder.principalOf("orgAdminUser", ORG_ID);
      orgAdmin.setRoles(new IdentityID[]{ ORG_ADMIN_ROLE });
      delegate = builder.principalOf("delegateUser", ORG_ID);

      ViewComponent components;

      try(InputStream in = ActionPermissionControllerRealTreeTest.class
         .getResourceAsStream("view-components-snapshot.json"))
      {
         components = new ObjectMapper().readValue(in, ViewComponent.class);
      }

      ComponentAuthorizationService componentService =
         Mockito.mock(ComponentAuthorizationService.class);
      Mockito.when(componentService.getComponentTree()).thenReturn(components);

      PortalThemesManager themes =
         new PortalThemesManager(Cluster.getInstance(), DataSpace.getDataSpace());
      themes.loadThemes();

      SecurityEngine engine = SecurityEngine.getSecurity();
      ActionPermissionService actionService =
         new ActionPermissionService(componentService, engine, themes);
      ResourcePermissionService permissionService =
         new ResourcePermissionService(engine.getSecurityProvider(), engine, null, null);
      controller = new ActionPermissionController(actionService, permissionService, engine);
   }

   @AfterAll
   static void teardownAll() {
      if(builder != null) {
         builder.teardown();
      }
   }

   @BeforeEach
   void setUp() {
      sutil = Mockito.mockStatic(SUtil.class, Mockito.CALLS_REAL_METHODS);
      sutil.when(SUtil::isMultiTenant).thenReturn(true);
      license = Mockito.mockStatic(LicenseManager.class, Mockito.CALLS_REAL_METHODS);
      license.when(LicenseManager::isEnterprise).thenReturn(true);
   }

   @AfterEach
   void tearDown() {
      ThreadContext.setContextPrincipal(null);
      license.close();
      sutil.close();
   }

   // sanity: the real tree of both personas is the org tree - no exclusions, no SECURITY_* nodes
   @Test
   void realTree_excludesSettingsGeneralAndSecurityTypes() {
      for(SRPrincipal p : List.of(orgAdmin, delegate)) {
         ThreadContext.setContextPrincipal(p);
         ActionTreeNode root = controller.getActionTree(p);
         List<ActionTreeNode> nodes = allNodes(root);

         assertTrue(nodes.stream().anyMatch(n -> isNode(n, ResourceType.EM_COMPONENT, SETTINGS_USERS)),
                    "settings/security/users must be in the tree of " + p);
         assertTrue(nodes.stream().anyMatch(n -> isNode(n, ResourceType.EM_COMPONENT, SETTINGS_SECURITY)),
                    "settings/security folder must be in the tree of " + p);
         assertFalse(nodes.stream().anyMatch(n -> isNode(n, ResourceType.EM_COMPONENT, SETTINGS_GENERAL)),
                     "settings/general must not be in the tree of " + p);
         assertFalse(nodes.stream().anyMatch(n -> n.type() != null && n.type().name().startsWith("SECURITY_")),
                     "no SECURITY_* node in the tree of " + p);
         assertFalse(nodes.stream().anyMatch(n -> n.actions().contains(ResourceAction.ADMIN)),
                     "no node offers ADMIN in the tree of " + p);
      }
   }

   // Bug #77251: the reporter's exact request body, org admin -> EM_COMPONENT settings/general ADMIN
   @Test
   void orgAdmin_adminOnSettingsGeneral_refusedAndNotWritten() throws Exception {
      ThreadContext.setContextPrincipal(orgAdmin);
      String json = "{\"permissions\": [{\"identityID\": {\"name\": \"orgAdminUser\", \"orgID\": \"" +
         ORG_ID + "\"}, \"baseName\": null, \"type\": 0, \"actions\": [\"ADMIN\"]}]," +
         "\"displayActions\": [\"ADMIN\"], \"hasOrgEdited\": true, \"securityEnabled\": true," +
         "\"requiresBoth\": false, \"derivePermissionLabel\": \"\", \"grantReadToAllVisible\": false," +
         "\"grantReadToAllLabel\": null, \"changed\": true}";
      ResourcePermissionModel body = new ObjectMapper().readValue(json, ResourcePermissionModel.class);

      assertThrows(java.lang.SecurityException.class, () -> controller.setPermissions(
         ResourceType.EM_COMPONENT.name(), SETTINGS_GENERAL, true, body, orgAdmin));

      assertFalse(hasUserGrant(ResourceType.EM_COMPONENT, SETTINGS_GENERAL, ResourceAction.ADMIN,
                               "orgAdminUser"), "no ADMIN grant may be stored");
      assertFalse(engine().checkPermission(orgAdmin, ResourceType.EM_COMPONENT, SETTINGS_GENERAL,
                                           ResourceAction.ACCESS));
   }

   // Bug #77252: delegate -> SECURITY_ORGANIZATION/<own org> ADMIN
   @Test
   void delegate_adminOnOwnSecurityOrganization_refusedAndNotWritten() throws Exception {
      ThreadContext.setContextPrincipal(delegate);
      String orgKey = new IdentityID(ORG_NAME, ORG_ID).convertToKey();
      ResourcePermissionModel body =
         model(EnumSet.of(ResourceAction.ADMIN), "delegateUser", EnumSet.of(ResourceAction.ADMIN));

      assertThrows(java.lang.SecurityException.class, () -> controller.setPermissions(
         ResourceType.SECURITY_ORGANIZATION.name(), orgKey, true, body, delegate));

      assertFalse(hasUserGrant(ResourceType.SECURITY_ORGANIZATION, orgKey, ResourceAction.ADMIN,
                               "delegateUser"), "no ADMIN grant may be stored");
      assertFalse(engine().checkPermission(
         delegate, ResourceType.SECURITY_USER, new IdentityID("victimUser", ORG_ID).convertToKey(),
         ResourceAction.ADMIN));
   }

   // Bug #77252 variant: delegate -> ADMIN on a visible EM node is refused as well
   @Test
   void delegate_adminOnVisibleEmNode_refusedAndNotWritten() throws Exception {
      ThreadContext.setContextPrincipal(delegate);
      ResourcePermissionModel body =
         model(EnumSet.of(ResourceAction.ADMIN), "delegateUser", EnumSet.of(ResourceAction.ADMIN));

      assertThrows(java.lang.SecurityException.class, () -> controller.setPermissions(
         ResourceType.EM_COMPONENT.name(), SETTINGS_USERS, true, body, delegate));

      assertFalse(hasUserGrant(ResourceType.EM_COMPONENT, SETTINGS_USERS, ResourceAction.ADMIN,
                               "delegateUser"));
   }

   // positive control: org admin grants ACCESS to another user on a visible, non-excluded leaf
   @Test
   void orgAdmin_accessToOtherUserOnVisibleLeaf_savedAndWritten() throws Exception {
      ThreadContext.setContextPrincipal(orgAdmin);
      ResourcePermissionModel body =
         model(EnumSet.of(ResourceAction.ACCESS), "granteeUser", EnumSet.of(ResourceAction.ACCESS));

      ResourcePermissionModel result = controller.setPermissions(
         ResourceType.EM_COMPONENT.name(), SETTINGS_USERS, true, body, orgAdmin);

      assertNotNull(result);
      assertEquals(EnumSet.of(ResourceAction.ACCESS), result.displayActions());
      assertTrue(hasUserGrant(ResourceType.EM_COMPONENT, SETTINGS_USERS, ResourceAction.ACCESS,
                              "granteeUser"), "the ACCESS grant must be stored");
   }

   // positive control: the same on a folder node (settings/security)
   @Test
   void orgAdmin_accessToOtherUserOnFolderNode_savedAndWritten() throws Exception {
      ThreadContext.setContextPrincipal(orgAdmin);
      ResourcePermissionModel body =
         model(EnumSet.of(ResourceAction.ACCESS), "granteeUser", EnumSet.of(ResourceAction.ACCESS));

      ResourcePermissionModel result = controller.setPermissions(
         ResourceType.EM_COMPONENT.name(), SETTINGS_SECURITY, true, body, orgAdmin);

      assertNotNull(result);
      assertTrue(hasUserGrant(ResourceType.EM_COMPONENT, SETTINGS_SECURITY, ResourceAction.ACCESS,
                              "granteeUser"), "the ACCESS grant must be stored");
   }

   private static boolean hasUserGrant(ResourceType type, String path, ResourceAction action,
                                       String user)
   {
      Permission perm = engine().getSecurityProvider().getPermission(type, path, ORG_ID);

      if(perm == null) {
         return false;
      }

      Set<IdentityID> grants = perm.getOrgScopedUserGrants(action, ORG_ID);
      return grants != null && grants.contains(new IdentityID(user, ORG_ID));
   }

   private static ResourcePermissionModel model(EnumSet<ResourceAction> displayActions,
                                                String user, EnumSet<ResourceAction> actions)
   {
      return ResourcePermissionModel.builder()
         .permissions(List.of(inetsoft.web.admin.security.ResourcePermissionTableModel.builder()
                                 .identityID(new IdentityID(user, ORG_ID))
                                 .type(Identity.Type.USER)
                                 .actions(actions)
                                 .build()))
         .displayActions(displayActions)
         .hasOrgEdited(true)
         .securityEnabled(true)
         .requiresBoth(false)
         .derivePermissionLabel("")
         .grantReadToAllVisible(false)
         .build();
   }

   private static boolean isNode(ActionTreeNode n, ResourceType type, String resource) {
      return n.type() == type && resource.equals(n.resource());
   }

   private static List<ActionTreeNode> allNodes(ActionTreeNode root) {
      List<ActionTreeNode> result = new ArrayList<>();
      Deque<ActionTreeNode> queue = new ArrayDeque<>(root.children());

      while(!queue.isEmpty()) {
         ActionTreeNode node = queue.removeFirst();
         result.add(node);
         queue.addAll(node.children());
      }

      return result;
   }

   private static SecurityEngine engine() {
      return SecurityEngine.getSecurity();
   }
}
