/*
 * This file is part of StyleBI.
 * Copyright (C) 2026  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package inetsoft.uql.jdbc;

import inetsoft.test.*;
import inetsoft.uql.XRepository;
import inetsoft.util.Plugins;
import inetsoft.util.credential.CredentialService;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.springframework.context.annotation.*;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.sql.*;
import java.util.*;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.mock;

/**
 * Bug #77581, MongoHelper had no text join order, so joins parsed from sql text (with
 * recorded ON clauses) were generated by the outer-last join walk. For a LEFT join followed
 * by an inner join that is not a simple chain, the walk wrote the inner join first and joined
 * the preserved table last with a RIGHT OUTER JOIN, which put the inner join (or a WHERE
 * comparison it moved into the from clause) on the null-supplying side of the outer join and
 * returned wrong rows. With a cycle (a lj b, a lj c where b.k &lt;&gt; c.k) it failed before
 * #77489 because a table was written twice, and returned wrong rows after it. MongoHelper now
 * uses text order: a left-deep chain is written flat, without the parentheses the unity driver
 * rejects (56305).
 */
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = { BaseTestConfiguration.class, PluginsTestConfiguration.class,
                                 SQLHelperMongoJoinOrderTest.Config.class },
                      initializers = ConfigurationContextInitializer.class)
@SreeHome
@Tag("core")
class SQLHelperMongoJoinOrderTest {
   // a data source with a real driver and URL needs the credential service, and the JDBC
   // driver types of Config to pick its SQL helper
   @Configuration
   @Import(CredentialService.class)
   static class Config {
      @Bean
      inetsoft.uql.util.Config config(Plugins plugins) {
         return new inetsoft.uql.util.Config(plugins);
      }

      @Bean
      XRepository repository() {
         return mock(XRepository.class);
      }
   }

   private static final String COLS3 = "select a.id, b.id, c.id ";
   private static final String COLS = "select a.id, b.id, c.id, d.id ";
   private static final String DB = "jdbc:derby:memory:bug77581";
   private static final String[] TABLES = { "a", "b", "c", "d" };

   // shapes that are not a simple chain, so the walk reordered them on MongoHelper
   static Stream<String> reorderedQueries() {
      return Stream.of(
         // the report: a cycle closed by a where clause comparison
         COLS3 + "from a left join b on a.id = b.id left join c on a.id = c.id where b.k <> c.k",
         COLS3 + "from a left join b on a.id = b.id left join c on a.id = c.id where b.k = c.k",
         COLS3 + "from a left join b on a.id = b.id left join c on a.id = c.id where b.k < c.k",
         COLS3 + "from a left join b on a.id = b.id left join c on a.id = c.id where b.k != c.k",
         // the report: a cycle closed by an inner join ON
         COLS + "from a left join b on a.id = b.id left join c on a.id = c.id join d on " +
            "b.id = d.id and c.k <> d.k",
         COLS + "from a left join b on a.id = b.id left join c on a.id = c.id join d on " +
            "b.id = d.id and c.k = d.k",
         COLS + "from a left join b on a.id = b.id left join c on a.id = c.id join d on " +
            "b.id = d.id and c.k < d.k",
         COLS + "from a left join b on a.id = b.id left join c on a.id = c.id join d on " +
            "b.id = d.id and c.k != d.k",
         // no cycle: the #77475 shape, and with a comparison in the inner ON
         COLS + "from a left join b on a.id = b.id join c on b.id = c.id left join d on a.id = d.id",
         COLS + "from a left join b on a.id = b.id join c on b.id = c.id and b.k <> c.k " +
            "left join d on a.id = d.id",
         COLS + "from a left join b on a.id = b.id join c on b.id = c.id and b.k = c.k " +
            "left join d on a.id = d.id",
         COLS + "from a left join b on a.id = b.id join c on b.id = c.id and b.k < c.k " +
            "left join d on a.id = d.id",
         COLS + "from a left join b on a.id = b.id join c on b.id = c.id and b.k != c.k " +
            "left join d on a.id = d.id",
         // an or and a not in the inner ON
         COLS + "from a left join b on a.id = b.id join c on b.id = c.id and " +
            "(b.k = c.k or c.k is null) left join d on a.id = d.id",
         COLS + "from a left join b on a.id = b.id join c on b.id = c.id and not (b.k = c.k) " +
            "left join d on a.id = d.id",
         // a parenthesized operand that adds a group of tables to one table
         COLS + "from a left join (b left join c on b.id = c.id) on a.id = b.id join d on " +
            "b.id = d.id",
         // comma separated groups linked by a where clause comparison
         COLS + "from a left join b on a.id = b.id, c left join d on c.id = d.id where b.k = d.k"
      );
   }

   static Stream<Arguments> reorderedQueryCases() {
      return reorderedQueries().flatMap(text -> Stream.of(Arguments.of(text, "mongo"),
                                                          Arguments.of(text, "mongo-ansi")));
   }

   @ParameterizedTest
   @MethodSource("reorderedQueryCases")
   void mongoKeepsTheTextOrder(String text, String type) throws Exception {
      String generated = generate(text, dataSource(type));
      assertSameRows(text, generated);
      // a left-deep chain needs no parentheses, which the unity driver rejects
      String from = from(generated);
      assertFalse(from.substring(0, (from + " where ").indexOf(" where ")).contains("("),
                  generated);
   }

   @ParameterizedTest
   @MethodSource("reorderedQueries")
   void mongoRegeneratedSqlRoundTrips(String text) throws Exception {
      // a reparsed outer join can swap its ON operands once, so require a fixed point after
      // the first regeneration
      JDBCDataSource ds = dataSource("mongo");
      String regenerated = generate(generate(text, ds), ds);
      assertEquals(regenerated, generate(regenerated, ds));
      assertSameRows(text, regenerated);
   }

   @Test
   void reportQueriesAreWrittenInTextOrder() throws Exception {
      JDBCDataSource ds = dataSource("mongo");

      // was: from b INNER JOIN c ON b.k <> c.k RIGHT OUTER JOIN a ON a.id = b.id AND a.id = c.id
      assertEquals("from a LEFT OUTER JOIN b ON a.id = b.id LEFT OUTER JOIN c ON a.id = c.id " +
                      "where b.k <> c.k",
                   from(generate(COLS3 + "from a left join b on a.id = b.id left join c on " +
                                 "a.id = c.id where b.k <> c.k", ds)));
      assertEquals("from a LEFT OUTER JOIN b ON a.id = b.id LEFT OUTER JOIN c ON a.id = c.id " +
                      "INNER JOIN d ON b.id = d.id AND c.k <> d.k",
                   from(generate(COLS + "from a left join b on a.id = b.id left join c on " +
                                 "a.id = c.id join d on b.id = d.id and c.k <> d.k", ds)));
      // was: from b INNER JOIN c ON b.id = c.id RIGHT OUTER JOIN a ON a.id = b.id LEFT OUTER
      // JOIN d ON a.id = d.id
      assertEquals("from a LEFT OUTER JOIN b ON a.id = b.id INNER JOIN c ON b.id = c.id " +
                      "LEFT OUTER JOIN d ON a.id = d.id",
                   from(generate(COLS + "from a left join b on a.id = b.id join c on " +
                                 "b.id = c.id left join d on a.id = d.id", ds)));
      // a != the parser found in an inner join ON stays in that ON, as on other databases
      assertEquals("from a LEFT OUTER JOIN b ON a.id = b.id INNER JOIN c ON b.id = c.id " +
                      "AND b.k != c.k LEFT OUTER JOIN d ON a.id = d.id",
                   from(generate(COLS + "from a left join b on a.id = b.id join c on " +
                                 "b.id = c.id and b.k != c.k left join d on a.id = d.id", ds)));
   }

   // the != shapes of SQLHelperNotEqualJoinTest (#77509) that MongoHelper wrote without text
   // join order: a != in an inner join ON stays in that ON, and a != in WHERE stays in WHERE
   @Test
   void mongoNotEqualFollowsTheTextOrder() throws Exception {
      String[][] cases = {
         { "from a right join b on a.id = b.id join c on b.id = c.id and a.k != c.k",
           "from a RIGHT OUTER JOIN b ON a.id = b.id INNER JOIN c ON b.id = c.id AND a.k != c.k" },
         { "from a left join b on a.id = b.id join c on a.id = c.id and a.k != c.k",
           "from a LEFT OUTER JOIN b ON a.id = b.id INNER JOIN c ON a.id = c.id AND a.k != c.k" },
         { "from a left join b on a.id = b.id join c on a.id = c.id where b.k != c.k",
           "from a LEFT OUTER JOIN b ON a.id = b.id INNER JOIN c ON a.id = c.id where b.k != c.k" },
      };

      for(String type : new String[] { "mongo", "mongo-ansi" }) {
         for(String[] test : cases) {
            String text = COLS3 + test[0];
            String generated = generate(text, dataSource(type));
            assertEquals(test[1], from(generated), type);
            assertSameRows(text, generated);
         }
      }
   }

   // a parenthesized join of two tables on the right of a join with a group of tables. If no
   // flat chain keeps its meaning, only the right group is written with parentheses, as in the
   // text, which the unity driver may reject (56305) instead of returning wrong rows. The join
   // order check of the parse refused the first three before, because the walk changed them
   // (it returned wrong rows for the first two when the structure was generated anyway)
   static Stream<Arguments> nestedGroupQueries() {
      return Stream.of(
         Arguments.of(COLS + "from a join b on a.id = b.id left join (c join d on c.id = d.id) " +
                         "on b.id = c.id",
                      "from a INNER JOIN b ON a.id = b.id LEFT OUTER JOIN (c INNER JOIN d ON " +
                         "c.id = d.id ) ON b.id = c.id"),
         Arguments.of(COLS + "from a left join b on a.id = b.id left join (c join d on " +
                         "c.id = d.id) on b.id = c.id",
                      "from a LEFT OUTER JOIN b ON a.id = b.id LEFT OUTER JOIN (c INNER JOIN d ON " +
                         "c.id = d.id ) ON b.id = c.id"),
         Arguments.of(COLS + "from a left join b on a.id = b.id left join (c join d on " +
                         "c.id = d.id) on a.id = c.id",
                      "from a LEFT OUTER JOIN b ON a.id = b.id LEFT OUTER JOIN (c INNER JOIN d ON " +
                         "c.id = d.id ) ON a.id = c.id"),
         // the inner join references the null-supplying table of the group
         Arguments.of(COLS + "from a join b on a.id = b.id join (c left join d on c.id = d.id) " +
                         "on b.id = d.id",
                      "from a INNER JOIN b ON a.id = b.id INNER JOIN (c LEFT OUTER JOIN d ON " +
                         "c.id = d.id ) ON b.id = d.id")
      );
   }

   @ParameterizedTest
   @MethodSource("nestedGroupQueries")
   void nestedGroupIsNotSilentlyWrong(String text, String expected) throws Exception {
      for(String type : new String[] { "mongo", "mongo-ansi" }) {
         String generated = generate(text, dataSource(type));
         assertEquals(expected, from(generated), type);
         assertSameRows(text, generated);
      }
   }

   // an inner join of a group and a chain of inner and left joins that only references the
   // first table of the chain is the same as the flat chain. MongoHelper wrote these flat
   // before (the walk found the order), and writes them flat in text order
   static Stream<Arguments> flatGroupQueries() {
      return Stream.of(
         Arguments.of(COLS + "from a left join b on a.id = b.id join (c left join d on " +
                         "c.id = d.id) on b.id = c.id",
                      "from a LEFT OUTER JOIN b ON a.id = b.id INNER JOIN c ON b.id = c.id " +
                         "LEFT OUTER JOIN d ON c.id = d.id"),
         Arguments.of(COLS + "from a join b on a.id = b.id join (c left join d on c.id = d.id) " +
                         "on b.id = c.id",
                      "from a INNER JOIN b ON a.id = b.id INNER JOIN c ON b.id = c.id " +
                         "LEFT OUTER JOIN d ON c.id = d.id"),
         // the step condition written from the right group
         Arguments.of(COLS + "from a left join b on a.id = b.id join (c left join d on " +
                         "c.id = d.id) on c.id = b.id",
                      "from a LEFT OUTER JOIN b ON a.id = b.id INNER JOIN c ON c.id = b.id " +
                         "LEFT OUTER JOIN d ON c.id = d.id"),
         Arguments.of(COLS + ", a2.id from a join b on a.id = b.id join (c join d on " +
                         "c.id = d.id) on b.id = c.id left join a a2 on a.id = a2.id",
                      "from a INNER JOIN b ON a.id = b.id INNER JOIN c ON b.id = c.id " +
                         "INNER JOIN d ON c.id = d.id LEFT OUTER JOIN a a2 ON a.id = a2.id")
      );
   }

   @ParameterizedTest
   @MethodSource("flatGroupQueries")
   void flatGroupIsWrittenFlat(String text, String expected) throws Exception {
      for(String type : new String[] { "mongo", "mongo-ansi" }) {
         String generated = generate(text, dataSource(type));
         assertEquals(expected, from(generated), type);
         assertSameRows(text, generated);
      }
   }

   @ParameterizedTest
   @MethodSource("flatGroupQueries")
   void otherDatabasesKeepTheNestedGroup(String text) throws Exception {
      // the flat chain is only for helpers without parentheses
      String generated = generate(text, dataSource("h2-ansi"));
      assertTrue(from(generated).contains(") INNER JOIN ("), generated);
      assertSameRows(text, generated);
   }

   @Test
   void mongoOutputWithoutTextOrderIsUnchanged() throws Exception {
      // a simple chain was kept by getLoyalJoins before, and is the same in text order
      String chain = COLS + "from a left join b on a.id = b.id join c on b.id = c.id join d on " +
         "c.id = d.id";
      String generated = generate(chain, dataSource("mongo"));
      assertEquals("from a LEFT OUTER JOIN b ON a.id = b.id INNER JOIN c ON b.id = c.id " +
                      "INNER JOIN d ON c.id = d.id", from(generated));
      assertSameRows(chain, generated);

      // no outer join, so no text order: inner joins keep the old output
      String inner = COLS + "from a join b on a.id = b.id join c on b.id = c.id join d on " +
         "a.id = d.id";
      generated = generate(inner, dataSource("mongo-ansi"));
      assertEquals("from a INNER JOIN b ON a.id = b.id INNER JOIN c ON b.id = c.id " +
                      "INNER JOIN d ON a.id = d.id", from(generated));
      assertSameRows(inner, generated);

      // joins without a recorded clause (query editor, data model) keep the outer-last walk,
      // written flat
      UniformSQL editor = parse(COLS + "from a left join b on a.id = b.id join c on " +
                                "b.id = c.id left join d on a.id = d.id", dataSource("mongo"));

      for(XJoin join : editor.getJoins()) {
         join.setJoinClause(XJoin.UNKNOWN_CLAUSE);
      }

      editor.clearSQLString();
      assertEquals("from b INNER JOIN c ON b.id = c.id RIGHT OUTER JOIN a ON a.id = b.id " +
                      "LEFT OUTER JOIN d ON a.id = d.id", from(normalize(editor.getSQLString())));
   }

   @ParameterizedTest
   @MethodSource("reorderedQueries")
   void otherDatabasesStillKeepTheRows(String text) throws Exception {
      // h2 and derby with the ANSI option already used text order; the sql is the same as the
      // text order sql of MongoHelper apart from the left-deep parentheses
      for(String type : new String[] { "h2", "h2-ansi", "derby-ansi" }) {
         String generated = generate(text, dataSource(type));
         assertSameRows(text, generated);
         assertEquals(from(generate(text, dataSource("mongo"))),
                      from(generated).replaceAll("^from \\(+", "from ").replace(" )", ""),
                      type);
      }
   }

   @BeforeAll
   static void createTables() throws SQLException {
      try(Connection conn = DriverManager.getConnection(DB + ";create=true");
          Statement stmt = conn.createStatement())
      {
         for(String table : TABLES) {
            stmt.executeUpdate("create table " + table + " (id int, k int)");
         }
      }
   }

   @AfterAll
   static void dropDatabase() {
      try {
         DriverManager.getConnection(DB + ";drop=true").close();
      }
      catch(SQLException ignore) {
         // derby reports a dropped database with an exception
      }
   }

   private static JDBCDataSource dataSource(String type) {
      JDBCDataSource ds = new JDBCDataSource();
      ds.setName("ds_" + type);
      ds.setProductVersion("19.0");

      switch(type.replace("-ansi", "")) {
      case "h2" -> {
         ds.setDriver("org.h2.Driver");
         ds.setURL("jdbc:h2:mem:test");
      }
      case "derby" -> {
         ds.setDriver("org.apache.derby.jdbc.EmbeddedDriver");
         ds.setURL("jdbc:derby:memory:test;create=true");
         ds.setProductVersion("10.17");
      }
      case "mongo" -> {
         ds.setDriver("mongodb.jdbc.MongoDriver");
         ds.setURL("jdbc:mongo://localhost:27017/test");
      }
      default -> throw new IllegalArgumentException(type);
      }

      ds.setAnsiJoin(type.endsWith("-ansi"));
      assertEquals(type.replace("-ansi", ""), SQLHelper.getSQLHelper(ds).getSQLHelperType());
      return ds;
   }

   // parse with the data source, as a query of the data source is parsed
   private static UniformSQL parse(String text, JDBCDataSource ds) throws Exception {
      UniformSQL sql = new UniformSQL();
      sql.setDataSource(ds);
      sql.parse(text, UniformSQL.PARSE_ALL, UniformSQL.PARSE_PERIOD);
      assertEquals(UniformSQL.PARSE_SUCCESS, sql.getParseResult(), text);
      assertFalse(sql.isLossy(), text);
      return sql;
   }

   private static String generate(String text, JDBCDataSource ds) throws Exception {
      UniformSQL sql = parse(text, ds);
      sql.clearSQLString();
      return normalize(sql.getSQLString());
   }

   private static String from(String generated) {
      return generated.substring(generated.indexOf(" from ") + 1);
   }

   private static String normalize(String sql) {
      return sql.replaceAll("\\s+", " ").trim();
   }

   /**
    * Runs both queries on random data with nulls, and requires the same rows from both.
    */
   private static void assertSameRows(String expected, String generated) throws SQLException {
      Random random = new Random(77581);

      try(Connection conn = DriverManager.getConnection(DB)) {
         for(int i = 0; i < 200; i++) {
            fillTables(conn, random);
            List<String> rows1 = rows(conn, expected);
            List<String> rows2 = rows(conn, generated);
            assertEquals(rows1, rows2, "dataset " + i + "\nexpected: " + expected +
               "\ngenerated: " + generated);
         }
      }
   }

   private static void fillTables(Connection conn, Random random) throws SQLException {
      try(Statement stmt = conn.createStatement()) {
         for(String table : TABLES) {
            stmt.executeUpdate("delete from " + table);
         }
      }

      for(String table : TABLES) {
         try(PreparedStatement insert =
                conn.prepareStatement("insert into " + table + " values (?, ?)"))
         {
            int count = random.nextInt(5);

            for(int i = 0; i < count; i++) {
               for(int column = 1; column <= 2; column++) {
                  int value = random.nextInt(4);

                  if(value == 0) {
                     insert.setNull(column, Types.INTEGER);
                  }
                  else {
                     insert.setInt(column, value);
                  }
               }

               insert.executeUpdate();
            }
         }
      }
   }

   // the result rows as a sorted multiset
   private static List<String> rows(Connection conn, String query) throws SQLException {
      List<String> rows = new ArrayList<>();

      try(Statement stmt = conn.createStatement(); ResultSet result = stmt.executeQuery(query)) {
         int columns = result.getMetaData().getColumnCount();

         while(result.next()) {
            StringBuilder row = new StringBuilder();

            for(int i = 1; i <= columns; i++) {
               row.append(result.getObject(i)).append('|');
            }

            rows.add(row.toString());
         }
      }

      Collections.sort(rows);
      return rows;
   }
}
