/*
 * This file is part of StyleBI.
 * Copyright (C) 2026  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package inetsoft.uql.jdbc;

import inetsoft.test.*;
import inetsoft.uql.XRepository;
import inetsoft.uql.util.Config;
import inetsoft.util.credential.CredentialService;
import inetsoft.util.credential.LocalPasswordCredential;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.sql.*;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyBoolean;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Bug #77718, SQLHelper.generateOrderByClause took any unqualified order by text starting
 * with ALIAS_ for an alias generated by JDBCSelection and quoted it whole as one name. An
 * expression (ALIAS_X + 1) became "ALIAS_X+1" on the default, Derby and Oracle helpers, and an
 * Oracle mixed case column ALIAS_x became "ALIAS_x", an unknown column either way. Only
 * ALIAS_ followed by digits, the name JDBCSelection generates, is taken for a generated alias.
 * The generated sql is executed on Derby, which folds an unquoted name to upper case as Oracle
 * does.
 */
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = { BaseTestConfiguration.class, SQLHelperOrderByGeneratedAliasTest.Beans.class },
                      initializers = ConfigurationContextInitializer.class)
@SreeHome
@Tag("core")
class SQLHelperOrderByGeneratedAliasTest {
   @BeforeAll
   static void createTable() throws SQLException {
      conn = DriverManager.getConnection("jdbc:derby:memory:bug77718;create=true");
      stmt = conn.createStatement();
      stmt.execute("create table t (ALIAS_X int, AB_X int, a int)");
      stmt.execute("insert into t values (3, 3, 1), (1, 1, 2), (2, 2, 3)");
   }

   @AfterAll
   static void dropTable() throws SQLException {
      stmt.close();
      conn.close();

      try {
         DriverManager.getConnection("jdbc:derby:memory:bug77718;drop=true");
      }
      catch(SQLException ignore) {
         // a successful drop is reported as an exception
      }
   }

   /**
    * An expression starting with ALIAS_ is not quoted, as an expression with any other prefix.
    * Was order by "ALIAS_X+1" desc (42X04) on each helper.
    */
   @Test
   void expressionStartingWithAliasPrefixIsNotQuoted() throws Exception {
      String query = "select a from t order by ALIAS_X + 1 desc";
      assertGenerated("default", query, "select a from t order by ALIAS_X+1 desc");
      assertGenerated("derby", query, "select a from t order by ALIAS_X+1 desc");
      assertGenerated("oracle", query, "select A from t order by ALIAS_X+1 desc");
   }

   /**
    * An Oracle column starting with ALIAS_ is not quoted, Oracle folds it to the upper case
    * column. Was order by "ALIAS_x" desc (ORA-00904), and "ALIAS_X", which ran.
    */
   @Test
   void oracleMixedCaseColumnStartingWithAliasPrefixIsNotQuoted() throws Exception {
      assertGenerated("oracle", "select a from t order by ALIAS_x desc", "select A from t order by ALIAS_x desc");
      // was "ALIAS_X", the same column on Oracle
      assertGenerated("oracle", "select a from t order by ALIAS_X desc", "select A from t order by ALIAS_X desc");
   }

   /**
    * The same order by with another prefix, a lower case prefix, and a column on the default
    * helper, the output before this change.
    */
   @Test
   void otherOrderByIsUnchanged() throws Exception {
      assertGenerated("default", "select a from t order by AB_X + 1 desc", "select a from t order by AB_X+1 desc");
      assertGenerated("derby", "select a from t order by AB_X + 1 desc", "select a from t order by AB_X+1 desc");
      assertGenerated("oracle", "select a from t order by AB_X + 1 desc", "select A from t order by AB_X+1 desc");
      assertGenerated("oracle", "select a from t order by AB_x desc", "select A from t order by AB_x desc");
      assertGenerated("default", "select a from t order by ALIAS_x desc", "select a from t order by ALIAS_x desc");
      assertGenerated("default", "select a from t order by alias_x + 1 desc",
                      "select a from t order by alias_x+1 desc");
   }

   /**
    * An alias generated for an expression whose alias isn't valid is still sorted as an alias.
    * PostgreSQL quotes the generated alias in the select list, so the order by must quote it
    * too, unquoted it would be folded to alias_0.
    */
   @Test
   void generatedAliasIsQuotedOnPostgreSQL() throws Exception {
      assertEquals("select \"a\"+1 as \"ALIAS_0\" from \"t\" order by \"ALIAS_0\" desc",
                   generatedAlias("postgresql", "select a + 1 as q from t order by q desc"));
   }

   /**
    * The generated alias of an expression, and of a distinct column through the derby path
    * that sorts by the alias instead of the column.
    */
   @Test
   void generatedAliasIsSortedByAlias() throws Exception {
      String query = "select a + 1 as q from t order by q desc";

      for(String key : new String[] { "default", "derby" }) {
         String generated = generatedAlias(key, query);
         assertEquals("select a+1 as ALIAS_0 from t order by ALIAS_0 desc", generated, key);
         assertEquals(List.of("[4]", "[3]", "[2]"), rows(generated), key);
      }

      String distinct = generatedAlias("derby", "select distinct t.a as q from t order by q desc");
      assertEquals("select distinct t.a as ALIAS_0 from t order by ALIAS_0 desc", distinct);
      assertEquals(List.of("[3]", "[2]", "[1]"), rows(distinct));
   }

   // the order by of the query, with the alias of its first column replaced by an alias that
   // isn't valid, so it's generated as ALIAS_0
   private static String generatedAlias(String key, String query) throws Exception {
      UniformSQL sql = parse(query, key);
      sql.getSelection().setAlias(0, "x\"y");
      sql.removeAllOrderByFields();
      sql.setOrderBy("x\"y", "desc");
      return regenerate(sql);
   }

   private static void assertGenerated(String key, String query, String expected) throws Exception {
      String generated = regenerate(parse(query, key));
      assertEquals(expected, generated, key + ": " + query);
      assertEquals(rows(query), rows(generated), key + ": " + query + " -> " + generated);
   }

   private static List<String> rows(String query) throws SQLException {
      List<String> rows = new ArrayList<>();

      try(ResultSet rs = stmt.executeQuery(query)) {
         int count = rs.getMetaData().getColumnCount();

         while(rs.next()) {
            List<Object> row = new ArrayList<>();

            for(int i = 1; i <= count; i++) {
               row.add(rs.getObject(i));
            }

            rows.add(row.toString());
         }
      }
      catch(SQLException ex) {
         throw new SQLException(query, ex);
      }

      return rows;
   }

   private static UniformSQL parse(String text, String key) throws Exception {
      UniformSQL sql = new UniformSQL();
      JDBCDataSource ds = source(key);

      if(ds != null) {
         sql.setDataSource(ds);
      }

      sql.parse(text, UniformSQL.PARSE_ALL, UniformSQL.PARSE_PERIOD);
      assertEquals(UniformSQL.PARSE_SUCCESS, sql.getParseResult(), text);
      assertFalse(sql.isLossy(), text);
      assertEquals(HELPERS.get(key), SQLHelper.getSQLHelper(sql).getClass(), key);
      return sql;
   }

   private static String regenerate(UniformSQL sql) {
      sql.clearSQLString();
      // the generated sql is pretty-printed
      return sql.getSQLString().replaceAll("\\s+", " ").trim();
   }

   private static JDBCDataSource source(String key) {
      return switch(key) {
         case "default" -> null;
         case "derby" -> dataSource("org.apache.derby.jdbc.EmbeddedDriver", "jdbc:derby:memory:x", "derby");
         case "oracle" -> dataSource("oracle.jdbc.OracleDriver", "jdbc:oracle:thin:@localhost:1521:x", "oracle");
         case "postgresql" -> dataSource("org.postgresql.Driver", "jdbc:postgresql://localhost/db", "postgresql");
         default -> throw new IllegalArgumentException(key);
      };
   }

   private static JDBCDataSource dataSource(String driver, String url, String product) {
      JDBCDataSource ds = new JDBCDataSource();
      ds.setName("ds77718" + product);
      ds.setDriver(driver);
      ds.setURL(url);
      ds.setRuntimeProductName(product);
      // otherwise the oracle helper asks the repository for it
      ds.setProductVersion("10.0");
      return ds;
   }

   private static final Map<String, Class<?>> HELPERS = Map.of(
      "default", SQLHelper.class, "derby", DerbyHelper.class, "oracle", OracleSQLHelper.class,
      "postgresql", PostgreSQLHelper.class);

   private static Connection conn;
   private static Statement stmt;

   // a JDBCDataSource creates its credential when it is constructed, and the derby helper
   // always asks the repository for the database version
   @Configuration
   static class Beans {
      @Bean
      Config config() {
         Config config = mock(Config.class);
         when(config.getJDBCType(any())).thenReturn("H2");
         return config;
      }

      @Bean
      CredentialService credentialService() {
         CredentialService service = mock(CredentialService.class);
         when(service.createCredential(any(), anyBoolean())).thenAnswer(inv -> new LocalPasswordCredential());
         return service;
      }

      @Bean
      XRepository repository() {
         return mock(XRepository.class);
      }
   }
}
