/*
 * This file is part of StyleBI.
 * Copyright (C) 2026  InetSoft Technology
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package inetsoft.uql.jdbc;

import inetsoft.report.lens.xnode.XNodeTableLens;
import inetsoft.sree.internal.cluster.Cluster;
import inetsoft.sree.security.IdentityID;
import inetsoft.storage.BlobStorageManager;
import inetsoft.test.*;
import inetsoft.uql.*;
import inetsoft.uql.erm.vpm.VpmCondition;
import inetsoft.uql.erm.vpm.VpmProcessor;
import inetsoft.uql.util.*;
import inetsoft.util.Plugins;
import inetsoft.util.Tool;
import inetsoft.util.credential.CredentialService;
import org.apache.derby.jdbc.EmbeddedDataSource;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import javax.sql.DataSource;
import java.io.*;
import java.lang.reflect.*;
import java.security.Principal;
import java.sql.*;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Bug #77755. A row-security (VPM) subquery that uses a niladic keyword-function
 * (current_date, current_timestamp, current_user) and a NULL_VALUE/EMPTY_STRING parameter is
 * parsed and regenerated by the VPM sentinel pass (#77706). The regenerated subquery must keep
 * the keyword unquoted: a quoted "current_timestamp" is a column reference, and the query fails.
 *
 * The query runs through the real {@link JDBCHandler#execute} with a user on Derby, as in
 * {@link XUtilSentinelVpmSubqueryTest}.
 */
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = { BaseTestConfiguration.class, SwapperTestConfiguration.class,
                                  XUtilSentinelVpmNiladicTest.JdbcConfig.class },
                      initializers = ConfigurationContextInitializer.class)
@SreeHome
@Tag("core")
class XUtilSentinelVpmNiladicTest {
   private static final String DB = "memory:bug77755vpm";
   private static final String NV = XConstants.CONDITION_NULL_VALUE;
   private static final String ES = XConstants.CONDITION_EMPTY_STRING;

   @Configuration
   static class JdbcConfig {
      // JDBCDataSource's constructor needs CredentialService, whose constructor is
      // package-private.
      @Bean
      public CredentialService credentialService() throws Exception {
         Constructor<CredentialService> ctor = CredentialService.class.getDeclaredConstructor();
         ctor.setAccessible(true);
         return ctor.newInstance();
      }

      @Bean
      public Plugins plugins(BlobStorageManager blobStorageManager, Cluster cluster,
                             ApplicationEventPublisher eventPublisher)
      {
         return new Plugins(blobStorageManager.getStorage("plugins", true), cluster,
                            eventPublisher);
      }

      @Bean
      public ConnectionPoolFactory connectionPoolFactory() {
         DataSource ds = recording(derby());
         ConnectionPoolFactory factory = mock(ConnectionPoolFactory.class);
         when(factory.getConnectionPool(any(), any())).thenReturn(ds);
         return factory;
      }

      @Bean
      public Drivers drivers(Plugins plugins, ConnectionPoolFactory connectionPoolFactory) {
         return new Drivers(plugins, connectionPoolFactory);
      }

      @Bean
      public Config config(Plugins plugins) {
         return new Config(plugins);
      }

      // DerbyHelper asks the repository for the product version
      @Bean
      public XRepository xRepository() {
         return mock(XRepository.class);
      }
   }

   @BeforeAll
   static void setUp() throws Exception {
      Field field = vpmProcessorField();
      oldVpmProcessor = field.get(null);
      field.set(null, new TestVpmProcessor());

      try(Connection conn = derby().getConnection(); Statement stmt = conn.createStatement()) {
         for(String table : new String[] { "a", "b" }) {
            try {
               stmt.executeUpdate("drop table " + table);
            }
            catch(SQLException ignore) {
               // first run
            }
         }

         stmt.executeUpdate("create table a (id int)");
         stmt.executeUpdate("insert into a values (1), (3), (5), (7), (9), (11)");
         // u is the database user (Derby's current_user is APP without a login), d and ts
         // are in the past except for 7 and 9
         stmt.executeUpdate("create table b (id int, k varchar(20), d date, ts timestamp, " +
                               "u varchar(20))");
         stmt.executeUpdate("insert into b values " +
            "(1, null, '2000-01-01', '2000-01-01 00:00:00', 'APP'), " +
            "(3, '', '2000-01-01', '2000-01-01 00:00:00', 'APP'), " +
            "(5, 'NULL_VALUE', '2000-01-01', '2000-01-01 00:00:00', 'APP'), " +
            "(7, null, '2999-01-01', '2999-01-01 00:00:00', 'APP'), " +
            "(9, '', '2999-01-01', '2999-01-01 00:00:00', 'APP'), " +
            "(11, null, '2000-01-01', '2000-01-01 00:00:00', 'X')");
      }
   }

   @AfterAll
   static void restoreVpmProcessor() throws Exception {
      vpmProcessorField().set(null, oldVpmProcessor);
   }

   @BeforeEach
   void clearVpm() {
      vpm = null;
   }

   // the date-based row filter of the report: b.k = $(p) and b.d < current_date
   @Test
   void currentDateSubquery() throws Exception {
      assertRows("select b.id from b where b.k = $(p) and b.d < current_date",
                 "current_date", List.of("1", "11"), List.of("3"));
   }

   @Test
   void currentTimestampSubquery() throws Exception {
      assertRows("select b.id from b where b.k = $(p) and b.ts < current_timestamp",
                 "current_timestamp", List.of("1", "11"), List.of("3"));
   }

   @Test
   void currentUserSubquery() throws Exception {
      assertRows("select b.id from b where b.k = $(p) and b.u = current_user",
                 "current_user", List.of("1", "7"), List.of("3", "9"));
   }

   // the keyword in the subquery's select list and in a nested IN subquery
   @Test
   void currentDateInSelectListAndNestedSubquery() throws Exception {
      assertRows("select b.id from b where b.k = $(p) and b.d < (select max(current_date) " +
                    "from a where a.id = 1)",
                 "current_date", List.of("1", "11"), List.of("3"));
      assertRows("select b.id from b where b.k = $(p) and b.id in " +
                    "(select b2.id from b b2 where b2.ts < current_timestamp)",
                 "current_timestamp", List.of("1", "11"), List.of("3"));
   }

   // the subquery as the condition editor saves it (an unparsed sql string), after a save and
   // reload, and parsed: each is regenerated for a sentinel, and the keyword stays unquoted
   private static void assertRows(String sub, String word, List<String> nvRows,
                                  List<String> esRows) throws Exception
   {
      for(UniformSQL value : new UniformSQL[] {
         new UniformSQL(sub, false), reload(new UniformSQL(sub, false)), parsed(sub) })
      {
         vpm = in(value);
         Run run = run(NV);
         assertEquals(nvRows, run.rows, run.condition);
         assertTrue(run.condition.contains("b.k is null"), run.condition);
         assertUnquoted(run, word);

         run = run(ES);
         assertEquals(esRows, run.rows, run.condition);
         assertTrue(run.condition.contains("b.k = ''"), run.condition);
         assertUnquoted(run, word);
      }
   }

   private static void assertUnquoted(Run run, String word) {
      assertTrue(run.condition.contains(word), run.condition);
      assertFalse(run.condition.contains("\"" + word + "\""), run.condition);
      assertFalse(executed.get().toLowerCase().contains("\"" + word + "\""), executed.get());
   }

   private static UniformSQL reload(UniformSQL saved) {
      try {
         StringWriter sw = new StringWriter();
         PrintWriter pw = new PrintWriter(sw);
         saved.writeXML(pw);
         pw.flush();
         UniformSQL reloaded = new UniformSQL();
         reloaded.parseXML(Tool.parseXML(new StringReader(sw.toString())).getDocumentElement());
         assertTrue(reloaded.hasSQLString());
         return reloaded;
      }
      catch(Exception ex) {
         throw new RuntimeException(ex);
      }
   }

   private static UniformSQL parsed(String sql) {
      try {
         UniformSQL usql = new UniformSQL();
         usql.parse(sql, UniformSQL.PARSE_ALL, UniformSQL.PARSE_PERIOD);
         assertEquals(UniformSQL.PARSE_SUCCESS, usql.getParseResult(), sql);
         usql.clearSQLString();
         return usql;
      }
      catch(Exception ex) {
         throw new RuntimeException(ex);
      }
   }

   private static VpmCondition in(UniformSQL sub) {
      return cond(new XBinaryCondition(new XExpression("a.id", XExpression.FIELD),
                                       new XExpression(sub, XExpression.SUBQUERY), "IN"));
   }

   private static VpmCondition cond(XFilterNode node) {
      VpmCondition cond = new VpmCondition("cond1");
      cond.setType(VpmCondition.TABLE);
      cond.setTable("a");
      cond.setCondition(node);
      return cond;
   }

   private static Run run(String p) throws Exception {
      VariableTable vars = new VariableTable();
      // as JDBCHandler and VpmUtil set them for the user
      vars.put("_USER_", "u1");
      vars.put("_ROLES_", new String[] { "r1", "r2" });
      vars.put("q", "'x'");

      if(p != null) {
         vars.put("p", p);
      }

      UniformSQL usql = parsed("select a.id from a");
      usql.setDataSource(dataSource());
      JDBCQuery query = new JDBCQuery();
      query.setName("bug77755vpm");
      query.setDataSource(dataSource());
      query.setSQLDefinition(usql);

      JDBCHandler handler = new JDBCHandler();
      handler.connect(query.getDataSource(), vars);
      condition.set(null);
      executed.set(null);
      XNode node = handler.execute(query, vars, USER, null);
      XNodeTableLens table = new XNodeTableLens(node);
      table.moreRows(Integer.MAX_VALUE);
      List<String> rows = new ArrayList<>();

      for(int r = 1; r < table.getRowCount(); r++) {
         rows.add(String.valueOf(table.getObject(r, 0)));
      }

      Collections.sort(rows);
      Run run = new Run();
      run.rows = rows;
      run.condition = norm(condition.get());
      assertNotNull(condition.get(), "the vpm condition wasn't applied");
      assertNotNull(executed.get(), "no sql executed");
      assertFalse(executed.get().contains("$("), executed.get());
      return run;
   }

   private static String norm(String sql) {
      return sql == null ? "" : sql.replaceAll("\\s+", " ").trim().toLowerCase();
   }

   /**
    * Applies the vpm condition of the test the way the enterprise VpmUtil.applyConditions
    * does: VpmCondition.evaluate generates the condition, which is ANDed to the WHERE as an
    * XExpressionCondition, and the sql string is cleared.
    */
   private static final class TestVpmProcessor extends VpmProcessor {
      @Override
      public XQuery applyConditions(XQuery query, VariableTable vars, boolean checkVariable,
                                    Principal user)
      {
         if(user == null || vpm == null) {
            return query;
         }

         try {
            JDBCQuery clone = (JDBCQuery) query.clone();
            UniformSQL usql = (UniformSQL) clone.getSQLDefinition();
            String cond = vpm.evaluate(null, new String[] { "a" }, new String[] { "a" },
                                       new String[] { "id" }, clone.getDataSource(), vars,
                                       user, checkVariable);
            condition.set(cond);

            if(cond != null) {
               usql.setSQLString(null);
               usql.combineWhereByAnd(new XExpressionCondition(
                  new XExpression(cond, XExpression.EXPRESSION)));
            }

            return clone;
         }
         catch(Exception ex) {
            throw new RuntimeException(ex);
         }
      }

      @Override
      public XQuery applyHiddenColumns(XQuery query, VariableTable vars, Principal user) {
         return query;
      }
   }

   private static Field vpmProcessorField() throws Exception {
      Field field = VpmProcessor.class.getDeclaredField("processor");
      field.setAccessible(true);
      return field;
   }

   private static JDBCDataSource dataSource() {
      JDBCDataSource ds = new JDBCDataSource();
      ds.setName("bug77755vpm");
      ds.setDriver("org.apache.derby.jdbc.EmbeddedDriver");
      ds.setURL("jdbc:derby:" + DB);
      ds.setRequireLogin(false);
      return ds;
   }

   private static DataSource derby() {
      EmbeddedDataSource ds = new EmbeddedDataSource();
      ds.setDatabaseName(DB);
      ds.setCreateDatabase("create");
      return ds;
   }

   // record the sql that reaches the connection
   private static DataSource recording(DataSource ds) {
      return proxy(DataSource.class, ds);
   }

   @SuppressWarnings("unchecked")
   private static <T> T proxy(Class<T> type, T target) {
      return (T) Proxy.newProxyInstance(
         XUtilSentinelVpmNiladicTest.class.getClassLoader(), new Class<?>[] { type },
         (p, method, args) -> {
            String name = method.getName();

            if(args != null && args.length > 0 && args[0] instanceof String &&
               (name.startsWith("prepare") || name.startsWith("execute")) &&
               ((String) args[0]).trim().toLowerCase().startsWith("select"))
            {
               executed.set((String) args[0]);
            }

            Object result;

            try {
               result = method.invoke(target, args);
            }
            catch(InvocationTargetException e) {
               throw e.getCause();
            }

            if(result instanceof Connection && type != Connection.class) {
               return proxy(Connection.class, (Connection) result);
            }

            if(result instanceof Statement && !(result instanceof PreparedStatement)) {
               return proxy(Statement.class, (Statement) result);
            }

            return result;
         });
   }

   private static final class Run {
      List<String> rows;
      String condition;
   }

   private static final Principal USER = new XPrincipal(new IdentityID("u1", "host-org"));
   private static final ThreadLocal<String> executed = new ThreadLocal<>();
   private static final ThreadLocal<String> condition = new ThreadLocal<>();
   private static volatile VpmCondition vpm;
   private static Object oldVpmProcessor;
}
